import React, { useEffect, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";
import TweetEmbed from 'react-tweet-embed';

import Header from "@/components/Header";
import Footer from "@/components/Footer";

export default function Example() {

  return (
    <>
      <div className="">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        <div className="flex bg-white min-h-screen pt-[100px]">
            <TweetEmbed tweetId="1674100846030618631" className="w-full" />
          
        </div>

        <Footer />
      </div>
    </>
  );
}
