import React from "react";
import Head from "next/head";
import Link from "next/link";

import Header from "@/components/Header";

import GoTop from "@/components/GoTop";
import Pagination from "@/components/Pagination";
import QuoteList from "@/components/QuoteList";
import Tags from "@/components/Tags";
import Footer from "@/components/Footer";
import SubscribeForm from "@/components/SubscribeForm";

export default function Quotes() {
  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />

      <main className="pt-[60px] md:pt-[80px] h-full">
        <div className="max-w-5xl mx-auto">
          <div className="px-6 pt-6 lg:hidden lg:mb-0 block">
            <form className="flex items-center relative">
              <div className="flex w-full items-center rounded-lg bg-gray-100 h-12 border px-1 py-3">
                <button
                  className="static inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-transparent text-gray-400 h-10 px-2 py-2 "
                  type="submit"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="3"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    className="h-5 w-5"
                  >
                    <circle cx="11" cy="11" r="8"></circle>
                    <path d="m21 21-4.3-4.3"></path>
                  </svg>
                </button>
                <input
                  className="relative flex h-12 bg-transparent px-1 py-3 text-md ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50 w-full lg:w-[600px] focus-visible:ring-transparent"
                  placeholder="Search for a Quote or People"
                />
              </div>
            </form>
          </div>
          <Tags />
          <div className="px-6 py-2 mb-5 space-y-4">
            <div>
              <QuoteList />
            </div>
            <Pagination />
          </div>
        </div>
        <SubscribeForm />
      </main>

      <Footer />
    </>
  );
}
