import React from "react";
import Head from "next/head";
import Link from "next/link";

import Header from "@/components/Header";

import GoTop from "@/components/GoTop";
import Sidebar from "@/components/Sidebar";
import Bottom from "@/components/Bottom";
import Pagination from "@/components/Pagination";
import QuoteList from "@/components/QuoteList";

export default function Quotes() {
  const tags = [
    "love",
    "hate",
    "live",
    "happy",
    "work",
    "will",
    "suffer",
    "rise",
    "persistent",
    "dream",
    "great",
    "people",
    "weak",
    "dazling",
    "best",
    "commitment",
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />

      <main className="lg:pl-72 pt-[80px] h-full">
        <div className="max-w-screen-2xl mx-auto">
          <div className="px-6 pt-6 lg:hidden lg:mb-0 block">
            <form className="flex items-center relative">
              <input
                className="flex h-10 border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 w-full lg:w-[600px] rounded-lg rounded-r-none focus-visible:ring-transparent pr-8"
                placeholder="Search for a course"
                value=""
              />
              <button
                className="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-sky-700 text-white hover:bg-sky-700/80 h-10 px-4 py-2 rounded-l-none"
                type="submit"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  className="lucide lucide-search h-4 w-4"
                >
                  <circle cx="11" cy="11" r="8"></circle>
                  <path d="m21 21-4.3-4.3"></path>
                </svg>
              </button>
            </form>
          </div>
          <div className="p-6 space-y-4">
            <div className="flex items-center gap-x-2 overflow-x-auto pb-2">
              <a href="/">
                <div className="py-2 px-3 text-sm rounded-md flex items-center gap-x-1 hover:bg-slate-200 transition cursor-pointer border-sky-700 bg-sky-500/10 text-sky-800">
                  <div className="truncate text-xs font-semibold">All</div>
                </div>
              </a>
              {tags.map((data, index) => (
                <Link href="/" key={index}>
                  <div className="py-2 px-3 text-sm bg-[#f1f5f9] rounded-md flex items-center gap-x-1 hover:bg-slate-200 transition cursor-pointer">
                    <div className="truncate text-xs font-semibold capitalize">
                      {data}
                    </div>
                  </div>
                </Link>
              ))}
            </div>
            <div>
              {/* <div className="grid sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3 2xl:grid-cols-4 gap-6">
                <a href="/projects/duolingo-clone">
                  <div className="group hover:bg-muted border transition overflow-hidden rounded-lg h-full flex flex-col">
                    <div className="flex-1">
                      
                      <div className="flex flex-col pt-2 px-3">
                        <div className="text-sm md:text-base font-medium group-hover:text-sky-700 transition line-clamp-2">
                          Duolingo Clone
                        </div>
                        <div className="my-3 flex items-center gap-x-2 text-xs">
                          <div className="flex items-center gap-x-1 text-slate-500">
                            <div className="rounded-full flex items-center justify-center bg-sky-100 p-1">
                              <svg
                                xmlns="http://www.w3.org/2000/svg"
                                width="24"
                                height="24"
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                stroke-width="2"
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                className="lucide lucide-book-open text-sky-700 h-4 w-4"
                              >
                                <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"></path>
                                <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"></path>
                              </svg>
                            </div>
                            <span>12 Chapters</span>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="px-3 pb-3">
                      <p className="text-sm font-medium text-slate-700">
                        Early access
                      </p>
                    </div>
                  </div>
                </a>
              </div> */}

              <QuoteList />
            </div>
            <Pagination />
          </div>
        </div>
      </main>

      <Sidebar />

      <Bottom />
    </>
  );
}
