import React, { useEffect, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Notice from "@/components/Notice";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SubscribeForm from "@/components/SubscribeForm";
import QuoteRandom from "@/components/QuoteRandom";
import Pagination from "@/components/Pagination";

export default function Persons() {
  const [alpha, setAlpha] = useState("a");

  const abjad = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
  ];

  return (
    <>
      <div className="">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        <div className="flex bg-white min-h-screen pt-[100px]">
          <div className="flex flex-row w-full">
            <div className="flex flex-1 flex-col items-center justify-center relative">
              <div className="flex flex-1 flex-col pb-18 max-w-md md:max-w-2xl ">
                <section className="w-full mx-auto  mt-2 md:mt-2 px-5 ">
                  <h5 className="font-semibold text-2xl md:text-3xl text-center ">
                    Person
                  </h5>
                  <p className="mt-3 font-normal text-lg text-gray-700 text-center ">
                    Browse through the most frequently asked questions.
                  </p>
                  <div className="px-8 z-9 md:container md:mx-auto md:px-0">
                    <div>
                      <div className="flex items-center justify-between pt-2 ">
                        <div className="top-0 py-3 flex overflow-x-auto scrollbars-hidden">
                          <div className="flex  space-x-3">
                            {abjad.map((huruf,i) => (
                              <Link href={`/authors/${huruf}`}>
                                <div
                                key={i}
                                  className={` px-4 py-2 border border-gray-300 cursor-pointer ${
                                    alpha === huruf
                                      ? "bg-orange-600 text-white border-orange-700"
                                      : "bg-white hover:bg-gray-200"
                                  }  font-normal`}
                                >
                                  <span className="text-sm font-semibold uppercase">
                                    {huruf}
                                  </span>
                                </div>
                              </Link>
                            ))}
                          </div>
                        </div>
                      </div>
                    </div>

                    <div className="">
                      <div className="flex justify-between">
                        <h1 className="text-md font-bold uppercase">{alpha}</h1>
                      </div>
                    </div>

                    <div className="py-10  columns-2 md:columns-4 lg:columns-6 ">
                      <div className="mb-4 rounded bg-[#f4f2ef] border group flex flex-col overflow-hidden justify-center shadow-md items-center cursor-zoom-in">
                        <div className="flex-grow py-2 lg:py-4 md:py-4 px-4">
                          <div className="flex justify-center items-center">
                            <div className="rounded-full p-4 border bg-white">
                              <svg
                                xmlns="http://www.w3.org/2000/svg"
                                viewBox="0 0 24 24"
                                fill="currentColor"
                                className="w-16 h-16"
                              >
                                <path
                                  fillRule="evenodd"
                                  d="M7.5 6a4.5 4.5 0 119 0 4.5 4.5 0 01-9 0zM3.751 20.105a8.25 8.25 0 0116.498 0 .75.75 0 01-.437.695A18.683 18.683 0 0112 22.5c-2.786 0-5.433-.608-7.812-1.7a.75.75 0 01-.437-.695z"
                                  clipRule="evenodd"
                                />
                              </svg>
                            </div>
                          </div>
                          <p className="leading-tight py-1 md:leading-tight text-black font-semibold text-center text-md md:text-md lg:text-2xl">
                            Alexis Mcalister
                          </p>
                          <div className="text-sm text-center">
                            football player
                          </div>
                        </div>
                      </div>
                      <div className="mb-4 rounded bg-[#f4f2ef] border group flex flex-col overflow-hidden justify-center shadow-md items-center cursor-zoom-in">
                        <div className="flex-grow py-2 lg:py-4 md:py-4 px-4">
                          <div className="flex justify-center items-center">
                            <div className="rounded-full p-4 border bg-white">
                              <svg
                                xmlns="http://www.w3.org/2000/svg"
                                viewBox="0 0 24 24"
                                fill="currentColor"
                                className="w-16 h-16"
                              >
                                <path
                                  fillRule="evenodd"
                                  d="M7.5 6a4.5 4.5 0 119 0 4.5 4.5 0 01-9 0zM3.751 20.105a8.25 8.25 0 0116.498 0 .75.75 0 01-.437.695A18.683 18.683 0 0112 22.5c-2.786 0-5.433-.608-7.812-1.7a.75.75 0 01-.437-.695z"
                                  clipRule="evenodd"
                                />
                              </svg>
                            </div>
                          </div>
                          <p className="leading-tight py-1 md:leading-tight text-black font-semibold text-center text-md md:text-md lg:text-2xl">
                            Alexis Mcalister
                          </p>
                          <div className="text-sm text-center">
                            football player
                          </div>
                        </div>
                      </div>
                      <div className="mb-4 rounded bg-[#f4f2ef] border group flex flex-col overflow-hidden justify-center shadow-md items-center cursor-zoom-in">
                        <div className="flex-grow py-2 lg:py-4 md:py-4 px-4">
                          <div className="flex justify-center items-center">
                            <div className="rounded-full p-4 border bg-white">
                              <svg
                                xmlns="http://www.w3.org/2000/svg"
                                viewBox="0 0 24 24"
                                fill="currentColor"
                                className="w-16 h-16"
                              >
                                <path
                                  fillRule="evenodd"
                                  d="M7.5 6a4.5 4.5 0 119 0 4.5 4.5 0 01-9 0zM3.751 20.105a8.25 8.25 0 0116.498 0 .75.75 0 01-.437.695A18.683 18.683 0 0112 22.5c-2.786 0-5.433-.608-7.812-1.7a.75.75 0 01-.437-.695z"
                                  clipRule="evenodd"
                                />
                              </svg>
                            </div>
                          </div>
                          <p className="leading-tight py-1 md:leading-tight text-black font-semibold text-center text-md md:text-md lg:text-2xl">
                            Alexis Mcalister
                          </p>
                          <div className="text-sm text-center">
                            football player
                          </div>
                        </div>
                      </div>
                      <div className="mb-4 rounded bg-[#f4f2ef] border group flex flex-col overflow-hidden justify-center shadow-md items-center cursor-zoom-in">
                        <div className="flex-grow py-2 lg:py-4 md:py-4 px-4">
                          <div className="flex justify-center items-center">
                            <div className="rounded-full p-4 border bg-white">
                              <svg
                                xmlns="http://www.w3.org/2000/svg"
                                viewBox="0 0 24 24"
                                fill="currentColor"
                                className="w-16 h-16"
                              >
                                <path
                                  fillRule="evenodd"
                                  d="M7.5 6a4.5 4.5 0 119 0 4.5 4.5 0 01-9 0zM3.751 20.105a8.25 8.25 0 0116.498 0 .75.75 0 01-.437.695A18.683 18.683 0 0112 22.5c-2.786 0-5.433-.608-7.812-1.7a.75.75 0 01-.437-.695z"
                                  clipRule="evenodd"
                                />
                              </svg>
                            </div>
                          </div>
                          <p className="leading-tight py-1 md:leading-tight text-black font-semibold text-center text-md md:text-md lg:text-2xl">
                            Alexis Mcalister
                          </p>
                          <div className="text-sm text-center">
                            football player
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </section>
                <Pagination />
                <QuoteRandom />
              </div>
              <SubscribeForm />
            </div>
          </div>
        </div>

        <Footer />
      </div>
    </>
  );
}
