import React, { useEffect, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Notice from "@/components/Notice";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SubscribeForm from "@/components/SubscribeForm";
import QuoteRandom from "@/components/QuoteRandom";
import Pagination from "@/components/Pagination";

import meme11 from "@/img/meme11.jpg";
import meme12 from "@/img/meme12.jpg";
import meme13 from "@/img/meme13.jpg";

import funny1 from "@/img/funny1.jpg";

export default function Blog() {

  return (
    <>
      <div className="">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        <div className="flex bg-white min-h-screen pt-14 md:pt-[100px]">
          <div className="flex flex-row w-full">
            <div className="flex flex-1 flex-col items-center justify-center relative">
              <div className="flex flex-1 flex-col pb-18 max-w-md md:max-w-2xl ">
                <section className="w-full mx-auto  mt-10 md:mt-10 px-5 ">
                  <h1 class="text-3xl font-bold tracking-tighter md:text-5xl lg:text-7xl">
                    1,000<span class="text-xl">s</span> more clicks <br /> with
                    Automated Link Previews!
                  </h1>
                  <p class="max-w-3xl mt-6 text-lg font-medium md:text-xl lg:text-2xl">
                    Say goodbye to Canva! Create a template, integrate it into
                    your site once, and focus on creating great content.
                  </p>

                  <div>
                    <div className="pt-6">
                      <Image src={funny1} />
                    </div>
                    <div className="flex w-full space-x-4">
                      <div>
                        <a
                          data-testid="cardlink-pilih-kategori-favoritmu"
                          className="text-tundora no-underline"
                          href="/campaign/yukinfaqyatim"
                          id="347492-347492"
                        >
                          <div className="my-[1em] mx-[0em] flex items-center w-full bg-white leading-[1.25em]">
                            <figure className="m-0 mr-5 flex aspect-[16/9] h-fit flex-1 items-center justify-center">
                              <Image
                                alt="Infaq Yatim: Kebahagiaan untuk 500 anak-anak Yatim"
                                src={meme13}
                                width="256"
                                height="144"
                                className="h-full w-full rounded object-fill"
                                style={{ color: "transparent" }}
                              />
                            </figure>
                            <div className="flex w-2/3 max-w-[45%] flex-1 flex-col space-x-y-1 md:space-y-2">
                              <span
                                className="my-[0.25em] mx-[0em] overflow-hidden break-words text-sm md:text-lg leading-tight md:leading-tight font-semibold text-tundora"
                                style={{
                                  display: "-webkit-box",
                                }}
                              >
                                80 Funny Work Memes to Keep You Laughing Through
                                the Week
                              </span>
                              <span className="text-xs md:text-lg leading-tight md:leading-tight break-words text-justify">
                                Whether you're waiting for the weekend or
                                commiserating about your job, these funny work
                                memes will help you cope
                              </span>
                            </div>
                          </div>
                          <div className="h-px bg-mercury"></div>
                        </a>
                        <a
                          data-testid="cardlink-pilih-kategori-favoritmu"
                          className="text-tundora no-underline"
                          href="/campaign/yukinfaqyatim"
                          id="347492-347492"
                        >
                          <div className="my-[1em] mx-[0em] flex items-center w-full bg-white leading-[1.25em]">
                            <figure className="m-0 mr-5 flex aspect-[16/9] h-fit flex-1 items-center justify-center">
                              <Image
                                alt="Infaq Yatim: Kebahagiaan untuk 500 anak-anak Yatim"
                                src={meme11}
                                width="100%"
                                height="100%"
                                className="h-full w-full rounded object-fill"
                                style={{ color: "transparent" }}
                              />
                            </figure>
                            <div className="flex w-2/3 max-w-[45%] flex-1 flex-col space-x-y-1 md:space-y-2">
                              <span
                                className="my-[0.25em] mx-[0em] overflow-hidden break-words text-sm md:text-lg leading-tight md:leading-tight font-semibold text-tundora"
                                style={{
                                  display: "-webkit-box",
                                }}
                              >
                                80 Funny Work Memes to Keep You Laughing Through
                                the Week
                              </span>
                              <span className="text-xs md:text-lg leading-tight md:leading-tight break-words text-justify">
                                Whether you're waiting for the weekend or
                                commiserating about your job, these funny work
                                memes will help you cope
                              </span>
                            </div>
                          </div>
                          <div className="h-px bg-mercury"></div>
                        </a>

                        <a
                          data-testid="cardlink-pilih-kategori-favoritmu"
                          className="text-tundora no-underline"
                          href="/campaign/yukinfaqyatim"
                          id="347492-347492"
                        >
                          <div className="my-[1em] mx-[0em] flex items-center w-full bg-white leading-[1.25em]">
                            <figure className="m-0 mr-5 flex aspect-[16/9] h-fit flex-1 items-center justify-center">
                              <Image
                                alt="Infaq Yatim: Kebahagiaan untuk 500 anak-anak Yatim"
                                src={meme12}
                                width="256"
                                height="144"
                                className="h-full w-full rounded object-fill"
                                style={{ color: "transparent" }}
                              />
                            </figure>
                            <div className="flex w-2/3 max-w-[45%] flex-1 flex-col space-x-y-1 md:space-y-2">
                              <span
                                className="my-[0.25em] mx-[0em] overflow-hidden break-words text-sm md:text-lg leading-tight md:leading-tight font-semibold text-tundora"
                                style={{
                                  display: "-webkit-box",
                                }}
                              >
                                80 Funny Work Memes to Keep You Laughing Through
                                the Week
                              </span>
                              <span className="text-xs md:text-lg leading-tight md:leading-tight break-words text-justify">
                                Whether you're waiting for the weekend or
                                commiserating about your job, these funny work
                                memes will help you cope
                              </span>
                            </div>
                          </div>
                          <div className="h-px bg-mercury"></div>
                        </a>
                      </div>
                    </div>
                  </div>
                  <Pagination />
                </section>

                <QuoteRandom />
              </div>
              <SubscribeForm />
            </div>
          </div>
        </div>

        <Footer />
      </div>
    </>
  );
}
