import React from "react";
import Head from "next/head";
import Link from "next/link";

import Header from "@/components/Header";
import GoTop from "@/components/GoTop";
import AuthorList from "@/components/AuthorList";
import Pagination from "@/components/Pagination";
import Footer from "@/components/Footer";
import SubscribeForm from "@/components/SubscribeForm";

export default function Author() {
  const letters = [
    {
      title: "a",
      status: true,
    },
    {
      title: "b",
      status: true,
    },
    {
      title: "c",
      status: true,
    },
    {
      title: "d",
      status: true,
    },
    {
      title: "e",
      status: true,
    },
    {
      title: "f",
      status: true,
    },
    {
      title: "g",
      status: true,
    },
    {
      title: "h",
      status: true,
    },
    {
      title: "i",
      status: true,
    },
    {
      title: "j",
      status: true,
    },
    {
      title: "k",
      status: true,
    },
    {
      title: "l",
      status: true,
    },
    {
      title: "m",
      status: true,
    },
    {
      title: "n",
      status: true,
    },
    {
      title: "o",
      status: true,
    },
    {
      title: "p",
      status: true,
    },
    {
      title: "q",
      status: true,
    },
    {
      title: "r",
      status: true,
    },
    {
      title: "s",
      status: true,
    },
    {
      title: "t",
      status: true,
    },
    {
      title: "u",
      status: true,
    },
    {
      title: "v",
      status: true,
    },
    {
      title: "w",
      status: true,
    },
    {
      title: "x",
      status: true,
    },
    {
      title: "y",
      status: true,
    },
    {
      title: "z",
      status: true,
    },
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />

      <main className="pt-[60px] bg-white md:pt-[80px] h-full">
        <div className="max-w-5xl mx-auto">
          <div className="px-6 pt-6 lg:hidden lg:mb-0 block">
          <form className="flex items-center relative">
              <div className="flex w-full items-center rounded-lg bg-gray-100 h-12 border px-1 py-3">
                <button
                  className="static inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-transparent text-gray-400 h-10 px-2 py-2 "
                  type="submit"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="3"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    className="h-5 w-5"
                  >
                    <circle cx="11" cy="11" r="8"></circle>
                    <path d="m21 21-4.3-4.3"></path>
                  </svg>
                </button>
                <input
                  className="relative flex h-12 bg-transparent px-1 py-3 text-md ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50 w-full lg:w-[600px] focus-visible:ring-transparent"
                  placeholder="Search for a Quote or People"
                />
              </div>
            </form>
          </div>
          <div className="p-6 space-y-4">
            <div>
              <span className="font-semibold text-black">
                Find a Author by its first letter:
              </span>
              <div className="flex flex-wrap justify-left mx-auto w-full md:w-12/12  items-center">
                {letters.map((data, index) => (
                  <Link
                    href={""}
                    key={index}
                    className="flex mr-2 mt-2 justify-center items-center mb-1.5 w-8 h-8 bg-white hover:bg-blue-800 px-2 py-1 border-2 text-gray-900 hover:text-white border-gray-900"
                  >
                    <span className="uppercase font-bold text-black">{data.title}</span>
                  </Link>
                ))}
              </div>
            </div>

            <div className="bg-white">
              <AuthorList />
            </div>
            <Pagination />
          </div>
        </div>
        <SubscribeForm />
      </main>

     <Footer />
    </>
  );
}
