import React from "react";
import Head from "next/head";
import Link from "next/link";

import Header from "@/components/Header";
import GoTop from "@/components/GoTop";
import AuthorList from "@/components/AuthorList";
import Pagination from "@/components/Pagination";
import Footer from "@/components/Footer";
import SubscribeForm from "@/components/SubscribeForm";
import Advertising from "@/components/Advertising";
import Search from "@/components/Search";

export default function Author() {
  const letters = [
    {
      title: "a",
      status: true,
    },
    {
      title: "b",
      status: true,
    },
    {
      title: "c",
      status: true,
    },
    {
      title: "d",
      status: true,
    },
    {
      title: "e",
      status: true,
    },
    {
      title: "f",
      status: true,
    },
    {
      title: "g",
      status: true,
    },
    {
      title: "h",
      status: true,
    },
    {
      title: "i",
      status: true,
    },
    {
      title: "j",
      status: true,
    },
    {
      title: "k",
      status: true,
    },
    {
      title: "l",
      status: true,
    },
    {
      title: "m",
      status: true,
    },
    {
      title: "n",
      status: true,
    },
    {
      title: "o",
      status: true,
    },
    {
      title: "p",
      status: true,
    },
    {
      title: "q",
      status: true,
    },
    {
      title: "r",
      status: true,
    },
    {
      title: "s",
      status: true,
    },
    {
      title: "t",
      status: true,
    },
    {
      title: "u",
      status: true,
    },
    {
      title: "v",
      status: true,
    },
    {
      title: "w",
      status: true,
    },
    {
      title: "x",
      status: true,
    },
    {
      title: "y",
      status: true,
    },
    {
      title: "z",
      status: true,
    },
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />

      <main className="pt-[60px] bg-white md:pt-[80px] h-full">
        <div className="max-w-5xl mx-auto">
        <Advertising />
          <div className="px-6 pt-6 lg:hidden lg:mb-0 block">
          <Search />
          </div>
          <div className="p-6 space-y-4">
            <div>
              <span className="font-semibold text-black">
                Find a Author by its first letter:
              </span>
              <div className="flex flex-wrap justify-left mx-auto w-full md:w-12/12  items-center">
                {letters.map((data, index) => (
                  <Link
                    href={""}
                    key={index}
                    className="flex mr-2 mt-2 justify-center items-center mb-1.5 w-8 h-8 bg-white hover:bg-blue-800 px-2 py-1 border-2 text-gray-900 hover:text-white border-gray-900"
                  >
                    <span className="uppercase font-bold text-black">{data.title}</span>
                  </Link>
                ))}
              </div>
            </div>

            <div className="bg-white">
              <AuthorList />
            </div>
            <Pagination />
          </div>
        </div>
        <SubscribeForm />
      </main>

     <Footer />
    </>
  );
}
