import React, { useEffect, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Notice from "@/components/Notice";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SubscribeForm from "@/components/SubscribeForm";
import QuoteRandom from "@/components/QuoteRandom";
import Pagination from "@/components/Pagination";

export default function Riddles() {
  return (
    <>
      <div className="">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        <div className="flex bg-white min-h-screen pt-[100px]">
          <div className="flex flex-row w-full">
            <div className="flex flex-1 flex-col items-center justify-center relative">
              <div className="flex flex-1 flex-col pb-18 max-w-md md:max-w-2xl ">
                <section className="w-full mx-auto  mt-10 md:mt-10 px-5 ">
                  <h5 className="font-semibold text-2xl md:text-3xl text-center ">
                    Riddles
                  </h5>
                  <p className="mt-3 font-normal text-lg text-gray-700 text-center ">
                    Browse through the most riddles.
                  </p>

                  <div className="py-10  columns-1 md:columns-2 lg:columns-3 ">
                    <div className="mb-4 rounded bg-[#4799eb] border group flex flex-col overflow-hidden justify-center shadow-md items-center cursor-zoom-in">
                      <div className="flex-grow py-2 lg:py-4 md:py-4 px-4">
                        <span className="flex justify-center py-1">
                          <span className="rounded-full p-1.5 border-2 border-white">
                            <svg
                              xmlns="http://www.w3.org/2000/svg"
                              className="text-white  icon icon-tabler icon-tabler-question-mark"
                              width="24"
                              height="24"
                              viewBox="0 0 24 24"
                              stroke-width="2"
                              stroke="currentColor"
                              fill="none"
                              stroke-linecap="round"
                              stroke-linejoin="round"
                            >
                              <path
                                stroke="none"
                                d="M0 0h24v24H0z"
                                fill="none"
                              ></path>
                              <path d="M8 8a3.5 3 0 0 1 3.5 -3h1a3.5 3 0 0 1 3.5 3a3 3 0 0 1 -2 3a3 4 0 0 0 -2 4"></path>
                              <path d="M12 19l0 .01"></path>
                            </svg>
                          </span>
                        </span>
                        <p className="leading-tight md:leading-snug  text-white text-center text-xl md:text-xl lg:text-2xl">
                          When I’m ripe, I’m green, when you eat me, I’m red,
                          and when you spit me out, I’m black. What am I?
                        </p>
                      </div>
                    </div>
                    <div className="mb-4 rounded bg-[#4799eb] border group flex flex-col overflow-hidden justify-center shadow-md items-center cursor-zoom-in">
                      <div className="flex-grow py-2 lg:py-4 md:py-4 px-4">
                        <span className="flex justify-center py-1">
                          <span className="rounded-full p-1.5 border-2 border-white">
                            <svg
                              xmlns="http://www.w3.org/2000/svg"
                              className="text-white  icon icon-tabler icon-tabler-question-mark"
                              width="24"
                              height="24"
                              viewBox="0 0 24 24"
                              stroke-width="2"
                              stroke="currentColor"
                              fill="none"
                              stroke-linecap="round"
                              stroke-linejoin="round"
                            >
                              <path
                                stroke="none"
                                d="M0 0h24v24H0z"
                                fill="none"
                              ></path>
                              <path d="M8 8a3.5 3 0 0 1 3.5 -3h1a3.5 3 0 0 1 3.5 3a3 3 0 0 1 -2 3a3 4 0 0 0 -2 4"></path>
                              <path d="M12 19l0 .01"></path>
                            </svg>
                          </span>
                        </span>
                        <p className="leading-tight md:leading-snug  text-white text-center text-xl md:text-xl lg:text-2xl">
                          What happens once in a lifetime, twice in a moment,
                          but never in one hundred years?
                        </p>
                      </div>
                    </div>
                    <div className="mb-4 rounded bg-[#4799eb] border group flex flex-col overflow-hidden justify-center shadow-md items-center cursor-zoom-in">
                      <div className="flex-grow py-2 lg:py-4 md:py-4 px-4">
                        <span className="flex justify-center py-1">
                          <span className="rounded-full p-1.5 border-2 border-white">
                            <svg
                              xmlns="http://www.w3.org/2000/svg"
                              className="text-white  icon icon-tabler icon-tabler-question-mark"
                              width="24"
                              height="24"
                              viewBox="0 0 24 24"
                              stroke-width="2"
                              stroke="currentColor"
                              fill="none"
                              stroke-linecap="round"
                              stroke-linejoin="round"
                            >
                              <path
                                stroke="none"
                                d="M0 0h24v24H0z"
                                fill="none"
                              ></path>
                              <path d="M8 8a3.5 3 0 0 1 3.5 -3h1a3.5 3 0 0 1 3.5 3a3 3 0 0 1 -2 3a3 4 0 0 0 -2 4"></path>
                              <path d="M12 19l0 .01"></path>
                            </svg>
                          </span>
                        </span>
                        <p className="leading-tight md:leading-snug  text-white text-center text-xl md:text-xl lg:text-2xl">
                          A boy and his father get into a car accident. When
                          they arrive at the hospital, the doctor sees the boy
                          and exclaims, “that’s my son!” How can this be?
                        </p>
                      </div>
                    </div>
                  </div>
                </section>
                <Pagination />
              </div>
              <SubscribeForm />
            </div>
          </div>
        </div>

        <Footer />
      </div>
    </>
  );
}
