import React, { useEffect, useState } from "react";
import Link from "next/link";
import Head from "next/head";

import Header from "@/components/Header";
import Nav from "@/components/Nav";
import Sidebar from "@/components/Sidebar";
import Bottom from "@/components/Bottom";

export default function Detail() {
  const [showAnswer, setShowAnswer] = useState(false);
  const toggleAnswer = () => {
    setShowAnswer((prev) => !prev);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="w-full h-screen">
        <div className="h-[0px] md:h-[66px]"></div>
        <div className="max-w-screen-5xl mx-auto">
          <div className="lg:flex p-0 w-full">
            {/* <div className="lg:w-72"></div> */}
            <div className="relative mx-auto w-full lg:w-[calc(100vh-200px)]2 lg:w-7/12 bg-[#0074d9]  h-[calc(100vh-66px)] min-h-screen pt-16 md:pt-[10px]">
              <div className="flex flex-col w-10/12 mx-auto items-center bg-[#0074d9] py-10 mb-4">
                <h1 className="relative mx-0 md:mx-auto text-2xl md:text-5xl md:leading-[60px] max-w-3xl m-auto text-white font-semibold  mt-4 sm:mt-6 mb-5 sm:mb-0">
                  A grandmother, two mothers, and two daughters went to a
                  baseball game together and bought one ticket each. How many
                  tickets did they buy in total?
                </h1>

                <div className="flex w-full max-w-3xl m-auto text-left mx-3 text-2xl md:text-5xl  md:leading-[60px]  text-[#fdfc3b] font-semibold text-center2 mt-4 sm:mt-6 mb-5 sm:mb-0">
                  <span>Three tickets </span>
                </div>
              </div>
              <Nav
                // next={idNext}
                // prev={idPrev}
                // riddId={riddId}
                // onClick={navClick}
                toggleAnswer={toggleAnswer}
                // updatePosition={updatePosition}
              />
            </div>
          </div>
        </div>
      </main>

      <Bottom />
    </>
  );
}
