import React, { useEffect, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Notice from "@/components/Notice";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SubscribeForm from "@/components/SubscribeForm";
import QuoteRandom from "@/components/QuoteRandom";

export default function Detail() {
  return (
    <>
      <div className="">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        <div className="flex bg-white min-h-screen pt-[100px]">
          <div className="flex flex-row w-full">
            <div className="flex flex-1 flex-col items-center justify-center relative">
              <div className="flex flex-1 flex-col pb-18 max-w-md md:max-w-2xl ">
                <section className="w-full mx-auto  mt-10 md:mt-10 px-5 ">
                  
                 
                  <div className="py-10  columns-1 ">
                    <div className="mb-4 rounded block bg-white border group flex flex-col overflow-hidden justify-center shadow-md items-center cursor-zoom-in">
                      <div className="flex-grow py-2 lg:py-4 md:py-4 px-4">
                        <p className="leading-tight md:leading-snug text-black text-center text-xl md:text-xl lg:text-2xl">
                          When we deny our emotion, it owns us. When we own our
                          emotion, we can rebuild and find our way through the
                          pain.
                        </p>
                        <div class=" px-2 py-4 flex justify-end">
                          <button class=" flex justify-between space-x-6 md:space-x-2">
                            <div class="flex space-x-2 ">
                              <span class="flex items-center justify-center text-sm text-[#171717BF] font-semibold">
                                Author
                              </span>
                            </div>
                          </button>
                        </div>
                      </div>
                    </div>
                    
                   
                  </div>
                </section>
              </div>
              <SubscribeForm />
            </div>
          </div>
        </div>

        <Footer />
      </div>
    </>
  );
}
