import React, { useState, useRef } from "react";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import TweetEmbed from "react-tweet-embed";
import styles from "../styles/Home.module.css";
import { Navigation, Pagination, Scrollbar, A11y } from "swiper";
import { Swiper, SwiperSlide } from "swiper/react";
import SwiperCore, { Autoplay } from "swiper";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Notice from "@/components/Notice";
import SubscribeForm from "@/components/SubscribeForm";
import QuoteLine from "@/components/QuoteLine";

import banner from "@/img/banner.jpg";
import kado from "@/img/kadountukasmat.jpg";
import kebaikan from "@/img/kebaikantanpaputus.jpg";
import amanah from "@/img/lazmizanamanah.jpg";
import arrowLeft from "@/img/icon_arrow-left.png";
import arrowRight from "@/img/icon_arrow-right.png";

import meme1 from "@/img/meme1.jpg";
import meme2 from "@/img/meme2.jpg";
import meme3 from "@/img/meme3.jpg";
import meme4 from "@/img/meme4.jpg";
import meme5 from "@/img/meme5.jpg";
import meme6 from "@/img/meme6.jpg";
import meme7 from "@/img/meme7.jpg";
import meme8 from "@/img/meme8.jpg";
import meme9 from "@/img/meme9.jpg";
import meme10 from "@/img/meme10.jpg";
import meme11 from "@/img/meme11.jpg";
import meme12 from "@/img/meme12.jpg";
import meme13 from "@/img/meme13.jpg";

import funny1 from "@/img/funny1.jpg";
import HomeSection from "@/components/HomeSection";

export default function Home() {
  SwiperCore.use([Autoplay]);

  let scrl = useRef(null);
  const shiftN = 230;
  const [scrollX, setscrollX] = useState(0);
  const [scrolEnd, setscrolEnd] = useState(false);

  const slide = (shift) => {
    scrl.current.scrollLeft += shift;
    setscrollX(scrollX + shift);

    if (
      Math.floor(scrl.current.scrollWidth - scrl.current.scrollLeft) <=
      scrl.current.offsetWidth
    ) {
      setscrolEnd(true);
    } else {
      setscrolEnd(false);
    }
  };

  const scrollCheck = () => {
    setscrollX(scrl.current.scrollLeft);
    if (
      Math.floor(scrl.current.scrollWidth - scrl.current.scrollLeft) <=
      scrl.current.offsetWidth
    ) {
      setscrolEnd(true);
    } else {
      setscrolEnd(false);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className="flex bg-white min-h-screen pt-[60px] md:pt-[100px]">
        <div className="flex flex-row w-full">
          <div className="flex flex-1 flex-col items-center justify-center relative">
            <div className="flex flex-1 flex-col pb-18 px-3 md:px-0 max-w-sm md:max-w-2xl">
              <Notice />
              <div id="template_horizontal-image-slider" className="hidden">
                <div className="default-banner-slider relative pt-[16px] mb-[1em] h-full">
                  <Swiper
                    modules={[Pagination, A11y]}
                    slidesPerView={1}
                    loop={true}
                    autoplay={{
                      delay: 4000,
                    }}
                    pagination={{ clickable: true }}
                  >
                    <SwiperSlide>
                      <Image src={banner} alt="" />
                    </SwiperSlide>
                    <SwiperSlide>
                      <Image src={kado} alt="" />
                    </SwiperSlide>
                    <SwiperSlide>
                      <Image src={amanah} alt="" />
                    </SwiperSlide>
                    <SwiperSlide>
                      <Image src={kebaikan} alt="" />
                    </SwiperSlide>
                  </Swiper>
                </div>
              </div>

              {/* <div className="py-2 pb-5 overflow-auto overflow-y-auto custom-scrollbar">
                <div className="inline-flex space-x-4">
                  <Link href="#">
                    <div className="relative flex-col justify-center w-32 md:w-48 space-y-2 border p-2 shadow-lg rounded">
                      <div className="relative block overflow-hidden bg-white shadow flex rounded">
                        <Image
                          src={meme1}
                          alt=""
                          className="relative w-full"
                        />
                      </div>

                      <div className="flex text-center2 pt-1 md:pt-1 text-sm capitalize">
                        <span className="text-[12px] font-semibold text-gray-800">
                          600 Yatim Dhuafa Ingin Jadi Penghafal Al-Qur&apos;an
                        </span>
                      </div>

                      <div className="flex flex-row justify-between text-center2 pt-1 md:pt-1 text-sm capitalize">
                        <span className="text-xs font-semibold">Pondok Al Ibadah</span>
                        <div className="">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            className="h-4 w-4 text-blue-500"
                            viewBox="0 0 20 20"
                            fill="currentColor"
                          >
                            <path
                              fillRule="evenodd"
                              d="M6.267 3.455a3.066 3.066 0 001.745-.723 3.066 3.066 0 013.976 0 3.066 3.066 0 001.745.723 3.066 3.066 0 012.812 2.812c.051.643.304 1.254.723 1.745a3.066 3.066 0 010 3.976 3.066 3.066 0 00-.723 1.745 3.066 3.066 0 01-2.812 2.812 3.066 3.066 0 00-1.745.723 3.066 3.066 0 01-3.976 0 3.066 3.066 0 00-1.745-.723 3.066 3.066 0 01-2.812-2.812 3.066 3.066 0 00-.723-1.745 3.066 3.066 0 010-3.976 3.066 3.066 0 00.723-1.745 3.066 3.066 0 012.812-2.812zm7.44 5.252a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                              clipRule="evenodd"
                            />
                          </svg>
                        </div>
                      </div>

                      <div className="overflow-hidden relative flex-1 rounded">
                        <div className="border-b-4 border-gray-300 rounded"></div>
                        <div className="absolute inset-x-0 top-0 -translate-x-4 border-b-4 border-blue-500 rounded transform hover:border-green-200"></div>
                      </div>

                      <div className="flex flex-col text-center2 pt-1 md:pt-1 text-sm capitalize">
                        <span className="text-[10px] font-semibold text-gray-600">Terkumpul</span>
                        <div>
                          <span className="text-sm pt-1 text-gray-900 font-bold">
                            Rp. 2.716.902.142
                          </span>
                        </div>
                      </div>
                    </div>
                  </Link>
                </div>
              </div> */}
              {/*  */}

              <div className="relative hidden">
                <div className="my-4 mx-0 flex items-center justify-between">
                  <h1
                    data-testid="title-pilihan-kitabisa"
                    // className="m-0 text-lg text-gray-900 font-bold"
                    className="mt-0 text-md md:text-lg text-gray-900 font-semibold md:font-bold"
                  >
                    Riddles
                  </h1>
                  <Link href={"/"}>
                    <span className="m-0 text-sm text-blue-400 cursor-pointer">
                      Lihat Lainnya
                    </span>
                  </Link>
                </div>
                <div className="relative">
                  {scrollX !== 0 && (
                    <div className=" top-[40%] left-0 ">
                      <Image
                        className="none absolute top-[40%] left-0 z-10 cursor-pointer"
                        src={arrowLeft}
                        alt="arrow left"
                        decoding="auto"
                        fetchpriority="auto"
                        onClick={() => slide(-shiftN)}
                      />
                    </div>
                  )}
                  {!scrolEnd && (
                    <div className=" top-[40%] right-0">
                      <Image
                        data-testid="arrow-right-pilihan-kitabisa"
                        className="none absolute top-[40%] right-0 z-10 cursor-pointer"
                        alt="arrow right"
                        src={arrowRight}
                        decoding="auto"
                        fetchpriority="auto"
                        onClick={() => slide(+shiftN)}
                      />
                    </div>
                  )}

                  {/*  */}
                  <div
                    className="mb-[1em] flex flex-row overflow-x-auto scroll-smooth"
                    ref={scrl}
                    onScroll={scrollCheck}
                  >
                    <div className="text‑inherit mt-0 mr-[1em] mb-[1em] cursor-pointer no-underline">
                      <div className="w-[250px]">
                        <div
                          className="flex flex-col rounded-[4px]"
                          style={{
                            boxShadow:
                              "rgba(152, 152, 152, 0.2) 0px 2px 8px 1px",
                            border: "0.5px solid rgba(0, 0, 0, 0.1)",
                          }}
                        >
                          <figure className="relative m-0 flex flex-1 items-center justify-center">
                            <Image
                              alt=""
                              src={meme5}
                              width="100"
                              height="100"
                              className="h-full w-full rounded object-cover"
                              style={{ color: "transparent" }}
                            />
                          </figure>
                        </div>
                      </div>
                    </div>
                    {/*  */}
                    <div className="text‑inherit mt-0 mr-[1em] mb-[1em] cursor-pointer no-underline">
                      <div className="w-[250px]">
                        <div
                          className="flex flex-col rounded-[4px]"
                          style={{
                            boxShadow:
                              "rgba(152, 152, 152, 0.2) 0px 2px 8px 1px",
                            border: "0.5px solid rgba(0, 0, 0, 0.1)",
                          }}
                        >
                          <figure className="relative m-0 flex flex-1 items-center justify-center">
                            <Image
                              alt=""
                              src={meme6}
                              width="100"
                              height="100"
                              className="h-full w-full rounded object-cover"
                              style={{ color: "transparent" }}
                            />
                          </figure>
                        </div>
                      </div>
                    </div>
                    {/*  */}
                    <div className="text‑inherit mt-0 mr-[1em] mb-[1em] cursor-pointer no-underline">
                      <div className="w-[250px]">
                        <div
                          className="flex flex-col rounded-[4px]"
                          style={{
                            boxShadow:
                              "rgba(152, 152, 152, 0.2) 0px 2px 8px 1px",
                            border: "0.5px solid rgba(0, 0, 0, 0.1)",
                          }}
                        >
                          <figure className="relative m-0 flex flex-1 items-center justify-center">
                            <Image
                              alt=""
                              src={meme7}
                              width="100"
                              height="100"
                              className="h-full w-full rounded object-cover"
                              style={{ color: "transparent" }}
                            />
                          </figure>
                        </div>
                      </div>
                    </div>
                    {/*  */}
                    <div className="text‑inherit mt-0 mr-[1em] mb-[1em] cursor-pointer no-underline">
                      <div className="w-[250px]">
                        <div
                          className="flex flex-col rounded-[4px]"
                          style={{
                            boxShadow:
                              "rgba(152, 152, 152, 0.2) 0px 2px 8px 1px",
                            border: "0.5px solid rgba(0, 0, 0, 0.1)",
                          }}
                        >
                          <figure className="relative m-0 flex flex-1 items-center justify-center">
                            <Image
                              alt=""
                              src={meme5}
                              width="100"
                              height="100"
                              className="h-full w-full rounded object-cover"
                              style={{ color: "transparent" }}
                            />
                          </figure>
                        </div>
                      </div>
                    </div>
                    {/*  */}
                    <div className="text‑inherit mt-0 mr-[1em] mb-[1em] cursor-pointer no-underline">
                      <div className="w-[250px]">
                        <div
                          className="flex flex-col rounded-[4px]"
                          style={{
                            boxShadow:
                              "rgba(152, 152, 152, 0.2) 0px 2px 8px 1px",
                            border: "0.5px solid rgba(0, 0, 0, 0.1)",
                          }}
                        >
                          <figure className="relative m-0 flex z-0 flex-1 items-center justify-center">
                            <Image
                              alt=""
                              src={meme8}
                              width="100"
                              height="100"
                              className="h-full z-0 w-full rounded object-cover"
                              style={{ color: "transparent" }}
                            />
                          </figure>
                        </div>
                      </div>
                    </div>
                    {/*  */}
                    <div
                      data-testid="link-lihat-semua-pilihan-kitabisa"
                      className="text‑inherit mt-0 mr-2 mb-4 cursor-pointer no-underline"
                    >
                      <div className="flex h-full w-[150px] flex-col justify-center text-center text-[#00aeef]">
                        <div className="text-base">
                          <svg
                            width="32px"
                            height="32px"
                            viewBox="0 0 24 24"
                            fill="none"
                            xmlns="http://www.w3.org/2000/svg"
                            role="img"
                            className="inline"
                          >
                            <path
                              fillRule="evenodd"
                              clipRule="evenodd"
                              d="M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18ZM1 12C1 5.925 5.925 1 12 1s11 4.925 11 11-4.925 11-11 11S1 18.075 1 12Z"
                              fill="#10A8E5"
                            ></path>
                            <path
                              d="M12.204 8.352c-.4-.443-.378-1.139.049-1.554a1.03 1.03 0 0 1 1.495.05l3.966 4.4a1.132 1.132 0 0 1 0 1.504l-3.966 4.4a1.03 1.03 0 0 1-1.495.05 1.131 1.131 0 0 1-.049-1.554l2.297-2.548H7.1a1.1 1.1 0 0 1 0-2.2h7.4l-2.296-2.548Z"
                              fill="#10A8E5"
                            ></path>
                          </svg>
                        </div>
                        <span className="m-0 text-base font-bold">
                          Lihat Semua
                        </span>
                      </div>
                    </div>
                    {/*  */}
                  </div>
                </div>
              </div>

              <div className="hidden">
                <h1
                  // className="mx-0 my-[1em] text-[16px] font-semibold leading-6 text-[#4a4a4a]"
                  className="md:mt-5 text-md md:text-lg text-gray-900 font-semibold md:font-bold"
                >
                  Blog
                </h1>
                <div className="flex w-full space-x-4">
                  <div>
                    <Link className="text-tundora no-underline" href="/">
                      <div className="my-[1em] mx-[0em] flex items-center w-full bg-white leading-[1.25em]">
                        <figure className="m-0 mr-2 md:mr-5 flex aspect-[10/9] md:aspect-[16/9] h-fit flex-1 items-center justify-center">
                          <Image
                            alt=""
                            src={meme13}
                            className="h-full w-full rounded object-cover"
                            style={{ color: "transparent" }}
                          />
                        </figure>
                        <div className="flex w-2/3 md:max-w-[55%] flex-1 flex-col space-y-1 md:space-y-2">
                          <span className="my-[0.25em] mx-[0em] overflow-hidden break-words text-md md:text-lg leading-tight md:leading-tight font-semibold">
                            80 Funny Work Memes to Keep You Laughing Through the
                            Week
                          </span>
                          <span className="text-sm md:text-lg leading-tight md:leading-tight tracking-tight break-words text-justify">
                            Whether you&apos;re waiting for the weekend or
                            commiserating about your job, these funny work memes
                            will help you cope
                          </span>
                        </div>
                      </div>
                      <div className="h-px bg-mercury"></div>
                    </Link>
                    <Link className="text-tundora no-underline" href="/">
                      <div className="my-[1em] mx-[0em] flex items-center w-full bg-white leading-[1.25em]">
                        <figure className="m-0 mr-2 md:mr-5 flex aspect-[10/9] md:aspect-[16/9] h-fit flex-1 items-center justify-center">
                          <Image
                            alt=""
                            src={meme11}
                            className="h-full w-full rounded object-cover"
                            style={{ color: "transparent" }}
                          />
                        </figure>
                        <div className="flex w-2/3 md:max-w-[55%] flex-1 flex-col space-y-1 md:space-y-2">
                          <span className="my-[0.25em] mx-[0em] overflow-hidden break-words text-md md:text-lg leading-tight md:leading-tight font-semibold">
                            80 Funny Work Memes to Keep You Laughing Through the
                            Week
                          </span>
                          <span className="text-sm md:text-lg leading-tight md:leading-tight tracking-tight break-words text-justify">
                            Whether you&apos;re waiting for the weekend or
                            commiserating about your job, these funny work memes
                            will help you cope
                          </span>
                        </div>
                      </div>
                      <div className="h-px bg-mercury"></div>
                    </Link>
                    {/*  */}
                    <div className="flex min-w-0 flex-1 flex-col py-2">
                      <div className="w-full rounded p-4 bg-[##14ada8]">
                        <div className="flex flex-col space-y-1 md:space-y-2">
                          <span className="my-[0.25em] mx-[0em] overflow-hidden break-words text-md md:text-lg leading-tight md:leading-tight font-semibold text-tundora">
                            80 Funny Work Memes to Keep You Laughing Through the
                            Week
                          </span>
                          <span className="text-sm md:text-lg leading-tight md:leading-tight break-words text-justify">
                            Whether you&apos;re waiting for the weekend or
                            commiserating about your job, these funny work memes
                            will help you cope
                          </span>
                        </div>
                        <div className="pt-2 ">
                          <TweetEmbed
                            tweetId="1674296643380826115"
                            className="w-1/2 md:w-full"
                          />
                        </div>
                      </div>
                      <div className="h-px bg-mercury"></div>
                    </div>
                    {/*  */}
                    {/* <Link
                      data-testid="cardlink-pilih-kategori-favoritmu"
                      className="text-tundora no-underline"
                      href="/campaign/yukinfaqyatim"
                      id="347492-347492"
                    >
                      <div className="my-[1em] mx-[0em] flex items-center w-full bg-white leading-[1.25em]">
                        <figure className="m-0 mr-5 flex aspect-[16/9] h-fit flex-1 items-center justify-center">
                          <Image
                            alt="Infaq Yatim: Kebahagiaan untuk 500 anak-anak Yatim"
                            src={meme12}
                            width="256"
                            height="144"
                            className="h-full w-full rounded object-cover"
                            style={{ color: "transparent" }}
                          />
                        </figure>
                        <div className="flex w-2/3 max-w-[45%] flex-1 flex-col space-x-y-1 md:space-y-2">
                          <span
                            className="my-[0.25em] mx-[0em] overflow-hidden break-words text-sm md:text-lg leading-tight md:leading-tight font-semibold text-tundora"
                            style={{
                              display: "-webkit-box",
                            }}
                          >
                            80 Funny Work Memes to Keep You Laughing Through the
                            Week
                          </span>
                          <span className="text-xs md:text-lg leading-tight md:leading-tight break-words text-justify">
                            Whether you&apos;re waiting for the weekend or
                            commiserating about your job, these funny work memes
                            will help you cope
                          </span>
                        </div>
                      </div>
                      <div className="h-px bg-mercury"></div>
                    </Link> */}
                    <Link className="text-tundora no-underline" href="/">
                      <div className="my-[1em] mx-[0em] flex items-center w-full bg-white leading-[1.25em]">
                        <figure className="m-0 mr-2 md:mr-5 flex aspect-[10/9] md:aspect-[16/9] h-fit flex-1 items-center justify-center">
                          <Image
                            alt=""
                            src={meme12}
                            className="h-full w-full rounded object-cover"
                            style={{ color: "transparent" }}
                          />
                        </figure>
                        <div className="flex w-2/3 md:max-w-[55%] flex-1 flex-col space-y-1 md:space-y-2">
                          <span className="my-[0.25em] mx-[0em] overflow-hidden break-words text-md md:text-lg leading-tight md:leading-tight font-semibold">
                            80 Funny Work Memes to Keep You Laughing Through the
                            Week
                          </span>
                          <span className="text-sm md:text-lg leading-tight md:leading-tight tracking-tight break-words text-justify">
                            Whether you&apos;re waiting for the weekend or
                            commiserating about your job, these funny work memes
                            will help you cope
                          </span>
                        </div>
                      </div>
                      <div className="h-px bg-mercury"></div>
                    </Link>
                  </div>
                </div>
              </div>

              <HomeSection />

              <section>
                <div
                  className="wrap mx-auto flex flex-col bg-white md:flex-row divide-y-2 md:divide-y-0 md:divide-x-2 divide-red"   
                >
                  <div
                    className="px-6 py-8 md:pt-16 md:pb-24 md:text-center md:w-1/2"
                    data-controller="animated-number"
                  >
                    <p>
                      <b
                        className="block font-heading text-5xl md:text-6xl text-black leading-snug mt-1 md:my-4"
                        data-target="animated-number.stat"
                        data-stat="1310904"
                      >
                        1,310,889
                      </b>
                      <span className="text-xl text-black">Quotes</span>
                    </p>
                  </div>
                  <div
                    className="px-6 py-8 md:pt-16 md:pb-24 md:text-center md:w-1/2"
                    data-controller="animated-number"
                  >
                    <p>
                      <b
                        className="block font-heading text-5xl md:text-6xl text-black leading-snug mt-1 md:my-4"
                        data-target="animated-number.stat"
                        data-stat="151284"
                      >
                        151,269
                      </b>
                      <span className="text-xl text-black">Famous People</span>
                    </p>
                  </div>
                </div>
              </section>

              <div className="hidden flex2 items-center justify-center px-3 py-2 space-x-1 md:space-x-3 my-[1em] mx-auto w-[160px] md:w-[190px] cursor-pointer rounded-full bg-[#e7f5ff]  text-center text-sm md:text-lg text-[#10a8e5]">
                <span>Lihat Semua</span>
                <span className="">
                  <svg
                    viewBox="0 0 24 24"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                    role="img"
                    className="w-3"
                  >
                    <path
                      fillRule="evenodd"
                      clipRule="evenodd"
                      d="M6.389 2.389a1.327 1.327 0 0 1 1.876 0l8.673 8.673a1.326 1.326 0 0 1 0 1.876l-8.673 8.673a1.327 1.327 0 0 1-1.876-1.876L14.124 12 6.389 4.265a1.327 1.327 0 0 1 0-1.876Z"
                      fill="#10A8E5"
                    ></path>
                  </svg>
                </span>
              </div>

              {/*  */}
              <QuoteLine />
            </div>
            <SubscribeForm />
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
