import React, { useState, useRef } from 'react'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Navigation, Pagination, Scrollbar, A11y } from 'swiper';
import { Swiper, SwiperSlide } from 'swiper/react';
import SwiperCore, { Autoplay } from 'swiper'
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';

import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Notice from '@/components/Notice'

import banner from '@/img/banner.jpg'
import kado from '@/img/kadountukasmat.jpg'
import kebaikan from '@/img/kebaikantanpaputus.jpg'
import amanah from '@/img/lazmizanamanah.jpg'
import arrowLeft from '@/img/icon_arrow-left.png'
import arrowRight from '@/img/icon_arrow-right.png'


export default function Home() {
  SwiperCore.use([Autoplay])

  let scrl = useRef(null);
  const shiftN = 230;
  const [scrollX, setscrollX] = useState(0);
  const [scrolEnd, setscrolEnd] = useState(false);

  const slide = (shift) => {
    scrl.current.scrollLeft += shift;
    setscrollX(scrollX + shift);

    if (
      Math.floor(scrl.current.scrollWidth - scrl.current.scrollLeft) <=
      scrl.current.offsetWidth
    ) {
      setscrolEnd(true);
    } else {
      setscrolEnd(false);
    }
  };

  const scrollCheck = () => {
    setscrollX(scrl.current.scrollLeft);
    if (
      Math.floor(scrl.current.scrollWidth - scrl.current.scrollLeft) <=
      scrl.current.offsetWidth
    ) {
      setscrolEnd(true);
    } else {
      setscrolEnd(false);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className="flex bg-white min-h-screen pt-[100px]">
    
        <div className="flex flex-row w-full">

          <div className="flex flex-1 flex-col items-center justify-center relative">
            <div className="flex flex-1 flex-col pb-18 max-w-md md:max-w-2xl">
            <Notice />
              <div id="template_horizontal-image-slider">
                <div className="default-banner-slider relative pt-[16px] mb-[1em] h-full">
                  <Swiper
                    modules={[Pagination, A11y]}
                    slidesPerView={1}
                    loop={true}
                    autoplay={{
                      delay: 4000,
                    }}
                    pagination={{ clickable: true }}
                  >
                    <SwiperSlide>
                      <Image src={banner} />
                    </SwiperSlide>
                    <SwiperSlide>
                      <Image src={kado} />
                    </SwiperSlide>
                    <SwiperSlide>
                      <Image src={amanah} />
                    </SwiperSlide>
                    <SwiperSlide>
                      <Image src={kebaikan} />
                    </SwiperSlide>
                  </Swiper>
                </div>
              </div>

              {/* <div className="py-2 pb-5 overflow-auto overflow-y-auto custom-scrollbar">
                <div className="inline-flex space-x-4">
                  <Link href="#">
                    <div className="relative flex-col justify-center w-32 md:w-48 space-y-2 border p-2 shadow-lg rounded">
                      <div className="relative block overflow-hidden bg-white shadow flex rounded">
                        <img
                          src="https://thediplomat.com/wp-content/uploads/2015/11/sizes/td-story-s-2/thediplomat_2015-11-11_15-17-05.jpg"
                          alt=""
                          className="relative w-full"
                        />
                      </div>

                      <div className="flex text-center2 pt-1 md:pt-1 text-sm capitalize">
                        <span className="text-[12px] font-semibold text-gray-800">
                          600 Yatim Dhuafa Ingin Jadi Penghafal Al-Qur'an
                        </span>
                      </div>

                      <div className="flex flex-row justify-between text-center2 pt-1 md:pt-1 text-sm capitalize">
                        <span className="text-xs font-semibold">Pondok Al Ibadah</span>
                        <div className="">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            className="h-4 w-4 text-blue-500"
                            viewBox="0 0 20 20"
                            fill="currentColor"
                          >
                            <path
                              fillRule="evenodd"
                              d="M6.267 3.455a3.066 3.066 0 001.745-.723 3.066 3.066 0 013.976 0 3.066 3.066 0 001.745.723 3.066 3.066 0 012.812 2.812c.051.643.304 1.254.723 1.745a3.066 3.066 0 010 3.976 3.066 3.066 0 00-.723 1.745 3.066 3.066 0 01-2.812 2.812 3.066 3.066 0 00-1.745.723 3.066 3.066 0 01-3.976 0 3.066 3.066 0 00-1.745-.723 3.066 3.066 0 01-2.812-2.812 3.066 3.066 0 00-.723-1.745 3.066 3.066 0 010-3.976 3.066 3.066 0 00.723-1.745 3.066 3.066 0 012.812-2.812zm7.44 5.252a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                              clipRule="evenodd"
                            />
                          </svg>
                        </div>
                      </div>

                      <div className="overflow-hidden relative flex-1 rounded">
                        <div className="border-b-4 border-gray-300 rounded"></div>
                        <div className="absolute inset-x-0 top-0 -translate-x-4 border-b-4 border-blue-500 rounded transform hover:border-green-200"></div>
                      </div>

                      <div className="flex flex-col text-center2 pt-1 md:pt-1 text-sm capitalize">
                        <span className="text-[10px] font-semibold text-gray-600">Terkumpul</span>
                        <div>
                          <span className="text-sm pt-1 text-gray-900 font-bold">
                            Rp. 2.716.902.142
                          </span>
                        </div>
                      </div>
                    </div>
                  </Link>
                </div>
              </div> */}
{/*  */}

              <div className='relative'>
                <div className="my-4 mx-0 flex items-center justify-between">
                  <h1 data-testid="title-pilihan-kitabisa" className="m-0 text-base text-gray-900 font-semibold">
                    Pilihan Kitabisa
                  </h1>
                  <a>
                    <span
                      data-testid="link-lihat-lainnya-pilihan-kitabisa"
                      aria-hidden="true"
                      className="m-0 text-sm text-blue-400"
                    >
                      Lihat Lainnya
                    </span>
                  </a>
                </div>
                <div className="relative">
                 
                {scrollX !== 0 && (
                  <div className='absolute top-[40%] left-0 '>
                  <Image
                    className="none absolute left-0 z-1 cursor-pointer"
                    aria-hidden="true"
                    src={arrowLeft}
                    alt="arrow left"
                    decoding="auto"
                    fetchpriority="auto"
                    onClick={() => slide(-shiftN)}
                  />
                  </div>
                )}
                {!scrolEnd && (
                  <div className='absolute top-[40%] right-0'>
                  <Image
                    data-testid="arrow-right-pilihan-kitabisa"
                    className="none absolute top-[40%] right-0 z-1 cursor-pointer"
                    aria-hidden="true"
                    alt="arrow right"
                    src={arrowRight}
                    decoding="auto"
                    fetchpriority="auto"
                    onClick={() => slide(+shiftN)}
                  />
                  </div>
                )}
                
                
                  {/*  */}
                  <div className="mb-[1em] flex flex-row overflow-x-auto scroll-smooth" ref={scrl} onScroll={scrollCheck}>
                    <div
                      aria-hidden="true"
                      data-testid="cardlink-pilihan-kitabisa"
                      className="text‑inherit mt-0 mr-[1em] mb-[1em] cursor-pointer no-underline"
                    >
                      <div className="w-[150px]">
                        <div
                          className="flex flex-col rounded-[4px]"
                          style={{
                            boxShadow: 'rgba(152, 152, 152, 0.2) 0px 2px 8px 1px',
                            border: '0.5px solid rgba(0, 0, 0, 0.1)',
                          }}
                        >
                          <figure className="relative m-0 flex flex-1 items-center justify-center">
                            <img
                              alt="Sedekah 1.000 Karpet Masjid ke Pelosok Negeri"
                              srcSet="https://thediplomat.com/wp-content/uploads/2015/11/sizes/td-story-s-2/thediplomat_2015-11-11_15-17-05.jpg"
                              src="https://thediplomat.com/wp-content/uploads/2015/11/sizes/td-story-s-2/thediplomat_2015-11-11_15-17-05.jpg"
                              width="100"
                              height="100"
                              decoding="async"
                              data-nimg="1"
                              className="h-[85px] w-full rounded-t object-cover"
                              loading="lazy"
                              style={{ color: 'transparent' }}
                            />
                          </figure>
                          <div className="p-[0.5em]">
                            <div className="min-h-[2.5em]">
                              <span
                                className="my-[0.25em] mx-[0em] overflow-hidden break-words text-sm font-semibold"
                                style={{
                                  display: '-webkit-box',
                                  webkitLineClamp: 2,
                                  webkitBoxOrient: 'vertical',
                                }}
                              >
                                Sedekah 1.000 Karpet Masjid ke Pelosok Negeri
                              </span>
                            </div>
                            <div className="my-[1em] mx-[0em]">
                              <div className="my-[0.25em] mx-[0em] flex w-full items-center align-middle text-xs text-[rgba(0,0,0,0.8)] ">
                                <span className="overflow-hidden text-ellipsis whitespace-nowrap">
                                  Masjid Nusantara
                                </span>
                                <img
                                  src="https://assets.kitabisa.cc/images/icons/icon__verified-org.svg"
                                  width="100"
                                  height="24"
                                  fetchpriority="low"
                                  decoding="auto"
                                  alt="icon badges"
                                  className="ml-[0.25em] h-3 w-[31px]"
                                />
                              </div>
                            </div>
                            <div className="my-[1em] mx-[0em]">
                              <div
                                data-testid="progressBar"
                                className="style__Track-sc-__sc-15i3suc-0 clbckc"
                              >
                                <div
                                  color="primary"
                                  data-testid="progressBarFiller"
                                  className="style__Filler-sc-__sc-15i3suc-1 bLoDes"
                                ></div>
                              </div>
                            </div>
                            <div className="flex flex-col">
                              <span className="text-[10px] font-normal leading-[1.75em] text-[rgba(0,0,0,0.8)]">
                                Terkumpul
                              </span>
                              <span className="text-[12px] font-bold leading-[1.75em]">
                                Rp 2.266.904.021
                              </span>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/*  */}
                    <div
                      aria-hidden="true"
                      data-testid="cardlink-pilihan-kitabisa"
                      className="text‑inherit mt-0 mr-[1em] mb-[1em] cursor-pointer no-underline"
                    >
                      <div className="w-[150px]">
                        <div
                          className="flex flex-col rounded-[4px]"
                          style={{
                            boxShadow: 'rgba(152, 152, 152, 0.2) 0px 2px 8px 1px',
                            border: '0.5px solid rgba(0, 0, 0, 0.1)',
                          }}
                        >
                          <figure className="relative m-0 flex flex-1 items-center justify-center">
                            <img
                              alt="Sedekah 1.000 Karpet Masjid ke Pelosok Negeri"
                              srcSet="https://thediplomat.com/wp-content/uploads/2015/11/sizes/td-story-s-2/thediplomat_2015-11-11_15-17-05.jpg"
                              src="https://thediplomat.com/wp-content/uploads/2015/11/sizes/td-story-s-2/thediplomat_2015-11-11_15-17-05.jpg"
                              width="100"
                              height="100"
                              decoding="async"
                              data-nimg="1"
                              className="h-[85px] w-full rounded-t object-cover"
                              loading="lazy"
                              style={{ color: 'transparent' }}
                            />
                          </figure>
                          <div className="p-[0.5em]">
                            <div className="min-h-[2.5em]">
                              <span
                                className="my-[0.25em] mx-[0em] overflow-hidden break-words text-sm font-semibold"
                                style={{
                                  display: '-webkit-box',
                                  webkitLineClamp: 2,
                                  webkitBoxOrient: 'vertical',
                                }}
                              >
                                Sedekah 1.000 Karpet Masjid ke Pelosok Negeri
                              </span>
                            </div>
                            <div className="my-[1em] mx-[0em]">
                              <div className="my-[0.25em] mx-[0em] flex w-full items-center align-middle text-xs text-[rgba(0,0,0,0.8)] ">
                                <span className="overflow-hidden text-ellipsis whitespace-nowrap">
                                  Masjid Nusantara
                                </span>
                                <img
                                  src="https://assets.kitabisa.cc/images/icons/icon__verified-org.svg"
                                  width="100"
                                  height="24"
                                  fetchpriority="low"
                                  decoding="auto"
                                  alt="icon badges"
                                  className="ml-[0.25em] h-3 w-[31px]"
                                />
                              </div>
                            </div>
                            <div className="my-[1em] mx-[0em]">
                              <div
                                data-testid="progressBar"
                                className="style__Track-sc-__sc-15i3suc-0 clbckc"
                              >
                                <div
                                  color="primary"
                                  data-testid="progressBarFiller"
                                  className="style__Filler-sc-__sc-15i3suc-1 bLoDes"
                                ></div>
                              </div>
                            </div>
                            <div className="flex flex-col">
                              <span className="text-[10px] font-normal leading-[1.75em] text-[rgba(0,0,0,0.8)]">
                                Terkumpul
                              </span>
                              <span className="text-[12px] font-bold leading-[1.75em]">
                                Rp 2.266.904.021
                              </span>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/*  */}
                    <div
                      aria-hidden="true"
                      data-testid="cardlink-pilihan-kitabisa"
                      className="text‑inherit mt-0 mr-[1em] mb-[1em] cursor-pointer no-underline"
                    >
                      <div className="w-[150px]">
                        <div
                          className="flex flex-col rounded-[4px]"
                          style={{
                            boxShadow: 'rgba(152, 152, 152, 0.2) 0px 2px 8px 1px',
                            border: '0.5px solid rgba(0, 0, 0, 0.1)',
                          }}
                        >
                          <figure className="relative m-0 flex flex-1 items-center justify-center">
                            <img
                              alt="Sedekah 1.000 Karpet Masjid ke Pelosok Negeri"
                              srcSet="https://thediplomat.com/wp-content/uploads/2015/11/sizes/td-story-s-2/thediplomat_2015-11-11_15-17-05.jpg"
                              src="https://thediplomat.com/wp-content/uploads/2015/11/sizes/td-story-s-2/thediplomat_2015-11-11_15-17-05.jpg"
                              width="100"
                              height="100"
                              decoding="async"
                              data-nimg="1"
                              className="h-[85px] w-full rounded-t object-cover"
                              loading="lazy"
                              style={{ color: 'transparent' }}
                            />
                          </figure>
                          <div className="p-[0.5em]">
                            <div className="min-h-[2.5em]">
                              <span
                                className="my-[0.25em] mx-[0em] overflow-hidden break-words text-sm font-semibold"
                                style={{
                                  display: '-webkit-box',
                                  webkitLineClamp: 2,
                                  webkitBoxOrient: 'vertical',
                                }}
                              >
                                Sedekah 1.000 Karpet Masjid ke Pelosok Negeri
                              </span>
                            </div>
                            <div className="my-[1em] mx-[0em]">
                              <div className="my-[0.25em] mx-[0em] flex w-full items-center align-middle text-xs text-[rgba(0,0,0,0.8)] ">
                                <span className="overflow-hidden text-ellipsis whitespace-nowrap">
                                  Masjid Nusantara
                                </span>
                                <img
                                  src="https://assets.kitabisa.cc/images/icons/icon__verified-org.svg"
                                  width="100"
                                  height="24"
                                  fetchpriority="low"
                                  decoding="auto"
                                  alt="icon badges"
                                  className="ml-[0.25em] h-3 w-[31px]"
                                />
                              </div>
                            </div>
                            <div className="my-[1em] mx-[0em]">
                              <div
                                data-testid="progressBar"
                                className="style__Track-sc-__sc-15i3suc-0 clbckc"
                              >
                                <div
                                  color="primary"
                                  data-testid="progressBarFiller"
                                  className="style__Filler-sc-__sc-15i3suc-1 bLoDes"
                                ></div>
                              </div>
                            </div>
                            <div className="flex flex-col">
                              <span className="text-[10px] font-normal leading-[1.75em] text-[rgba(0,0,0,0.8)]">
                                Terkumpul
                              </span>
                              <span className="text-[12px] font-bold leading-[1.75em]">
                                Rp 2.266.904.021
                              </span>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/*  */}
                    <div
                      aria-hidden="true"
                      data-testid="cardlink-pilihan-kitabisa"
                      className="text‑inherit mt-0 mr-[1em] mb-[1em] cursor-pointer no-underline"
                    >
                      <div className="w-[150px]">
                        <div
                          className="flex flex-col rounded-[4px]"
                          style={{
                            boxShadow: 'rgba(152, 152, 152, 0.2) 0px 2px 8px 1px',
                            border: '0.5px solid rgba(0, 0, 0, 0.1)',
                          }}
                        >
                          <figure className="relative m-0 flex flex-1 items-center justify-center">
                            <img
                              alt="Sedekah 1.000 Karpet Masjid ke Pelosok Negeri"
                              srcSet="https://thediplomat.com/wp-content/uploads/2015/11/sizes/td-story-s-2/thediplomat_2015-11-11_15-17-05.jpg"
                              src="https://thediplomat.com/wp-content/uploads/2015/11/sizes/td-story-s-2/thediplomat_2015-11-11_15-17-05.jpg"
                              width="100"
                              height="100"
                              decoding="async"
                              data-nimg="1"
                              className="h-[85px] w-full rounded-t object-cover"
                              loading="lazy"
                              style={{ color: 'transparent' }}
                            />
                          </figure>
                          <div className="p-[0.5em]">
                            <div className="min-h-[2.5em]">
                              <span
                                className="my-[0.25em] mx-[0em] overflow-hidden break-words text-sm font-semibold"
                                style={{
                                  display: '-webkit-box',
                                  webkitLineClamp: 2,
                                  webkitBoxOrient: 'vertical',
                                }}
                              >
                                Sedekah 1.000 Karpet Masjid ke Pelosok Negeri
                              </span>
                            </div>
                            <div className="my-[1em] mx-[0em]">
                              <div className="my-[0.25em] mx-[0em] flex w-full items-center align-middle text-xs text-[rgba(0,0,0,0.8)] ">
                                <span className="overflow-hidden text-ellipsis whitespace-nowrap">
                                  Masjid Nusantara
                                </span>
                                <img
                                  src="https://assets.kitabisa.cc/images/icons/icon__verified-org.svg"
                                  width="100"
                                  height="24"
                                  fetchpriority="low"
                                  decoding="auto"
                                  alt="icon badges"
                                  className="ml-[0.25em] h-3 w-[31px]"
                                />
                              </div>
                            </div>
                            <div className="my-[1em] mx-[0em]">
                              <div
                                data-testid="progressBar"
                                className="style__Track-sc-__sc-15i3suc-0 clbckc"
                              >
                                <div
                                  color="primary"
                                  data-testid="progressBarFiller"
                                  className="style__Filler-sc-__sc-15i3suc-1 bLoDes"
                                ></div>
                              </div>
                            </div>
                            <div className="flex flex-col">
                              <span className="text-[10px] font-normal leading-[1.75em] text-[rgba(0,0,0,0.8)]">
                                Terkumpul
                              </span>
                              <span className="text-[12px] font-bold leading-[1.75em]">
                                Rp 2.266.904.021
                              </span>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/*  */}
                    <div
                      aria-hidden="true"
                      data-testid="cardlink-pilihan-kitabisa"
                      className="text‑inherit mt-0 mr-[1em] mb-[1em] cursor-pointer no-underline"
                    >
                      <div className="w-[150px]">
                        <div
                          className="flex flex-col rounded-[4px]"
                          style={{
                            boxShadow: 'rgba(152, 152, 152, 0.2) 0px 2px 8px 1px',
                            border: '0.5px solid rgba(0, 0, 0, 0.1)',
                          }}
                        >
                          <figure className="relative m-0 flex flex-1 items-center justify-center">
                            <img
                              alt="Sedekah 1.000 Karpet Masjid ke Pelosok Negeri"
                              srcSet="https://thediplomat.com/wp-content/uploads/2015/11/sizes/td-story-s-2/thediplomat_2015-11-11_15-17-05.jpg"
                              src="https://thediplomat.com/wp-content/uploads/2015/11/sizes/td-story-s-2/thediplomat_2015-11-11_15-17-05.jpg"
                              width="100"
                              height="100"
                              decoding="async"
                              data-nimg="1"
                              className="h-[85px] w-full rounded-t object-cover"
                              loading="lazy"
                              style={{ color: 'transparent' }}
                            />
                          </figure>
                          <div className="p-[0.5em]">
                            <div className="min-h-[2.5em]">
                              <span
                                className="my-[0.25em] mx-[0em] overflow-hidden break-words text-sm font-semibold"
                                style={{
                                  display: '-webkit-box',
                                  webkitLineClamp: 2,
                                  webkitBoxOrient: 'vertical',
                                }}
                              >
                                Sedekah 1.000 Karpet Masjid ke Pelosok Negeri
                              </span>
                            </div>
                            <div className="my-[1em] mx-[0em]">
                              <div className="my-[0.25em] mx-[0em] flex w-full items-center align-middle text-xs text-[rgba(0,0,0,0.8)] ">
                                <span className="overflow-hidden text-ellipsis whitespace-nowrap">
                                  Masjid Nusantara
                                </span>
                                <img
                                  src="https://assets.kitabisa.cc/images/icons/icon__verified-org.svg"
                                  width="100"
                                  height="24"
                                  fetchpriority="low"
                                  decoding="auto"
                                  alt="icon badges"
                                  className="ml-[0.25em] h-3 w-[31px]"
                                />
                              </div>
                            </div>
                            <div className="my-[1em] mx-[0em]">
                              <div
                                data-testid="progressBar"
                                className="style__Track-sc-__sc-15i3suc-0 clbckc"
                              >
                                <div
                                  color="primary"
                                  data-testid="progressBarFiller"
                                  className="style__Filler-sc-__sc-15i3suc-1 bLoDes"
                                ></div>
                              </div>
                            </div>
                            <div className="flex flex-col">
                              <span className="text-[10px] font-normal leading-[1.75em] text-[rgba(0,0,0,0.8)]">
                                Terkumpul
                              </span>
                              <span className="text-[12px] font-bold leading-[1.75em]">
                                Rp 2.266.904.021
                              </span>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/*  */}
                    <div
                      data-testid="link-lihat-semua-pilihan-kitabisa"
                      aria-hidden="true"
                      className="text‑inherit mt-0 mr-2 mb-4 cursor-pointer no-underline"
                    >
                      <div className="flex h-full w-[150px] flex-col justify-center text-center text-[#00aeef]">
                        <div className="text-base">
                          <svg
                            width="32px"
                            height="32px"
                            viewBox="0 0 24 24"
                            fill="none"
                            xmlns="http://www.w3.org/2000/svg"
                            role="img"
                            className="inline"
                          >
                            <path
                              fill-rule="evenodd"
                              clip-rule="evenodd"
                              d="M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18ZM1 12C1 5.925 5.925 1 12 1s11 4.925 11 11-4.925 11-11 11S1 18.075 1 12Z"
                              fill="#10A8E5"
                            ></path>
                            <path
                              d="M12.204 8.352c-.4-.443-.378-1.139.049-1.554a1.03 1.03 0 0 1 1.495.05l3.966 4.4a1.132 1.132 0 0 1 0 1.504l-3.966 4.4a1.03 1.03 0 0 1-1.495.05 1.131 1.131 0 0 1-.049-1.554l2.297-2.548H7.1a1.1 1.1 0 0 1 0-2.2h7.4l-2.296-2.548Z"
                              fill="#10A8E5"
                            ></path>
                          </svg>
                        </div>
                        <span className="m-0 text-base font-bold">Lihat Semua</span>
                      </div>
                    </div>
                    {/*  */}
                  </div>
                </div>
              </div>

              <div>
              <h1 data-testid="title-pilih-kategori-favoritmu" class="mx-0 my-[1em] text-[16px] font-semibold leading-6 text-[#4a4a4a]">Pilih Kategori Favoritmu</h1>
                <div className='flex w-full space-x-4'>
                  <div className='w-3/6 bg-pink-200'></div>
                
                <div>
                  <a
                    data-testid="cardlink-pilih-kategori-favoritmu"
                    className="text-tundora no-underline"
                    href="/campaign/yukinfaqyatim"
                    id="347492-347492"
                  >
                    <div className="my-[1em] mx-[0em] flex items-center bg-white leading-[1.25em]">
                      <figure className="m-0 mr-5 flex aspect-[16/9] h-fit flex-1 items-center justify-center">
                        <img
                          alt="Infaq Yatim: Kebahagiaan untuk 500 anak-anak Yatim"
                          srcSet="https://thediplomat.com/wp-content/uploads/2015/11/sizes/td-story-s-2/thediplomat_2015-11-11_15-17-05.jpg"
                          src="https://thediplomat.com/wp-content/uploads/2015/11/sizes/td-story-s-2/thediplomat_2015-11-11_15-17-05.jpg"
                          width="256"
                          height="144"
                          decoding="async"
                          data-nimg="1"
                          className="h-full w-full rounded object-fill"
                          loading="lazy"
                          style={{ color: 'transparent' }}
                        />
                      </figure>
                      <div className="flex max-w-[45%] flex-1 flex-col justify-between">
                        <span
                          className="my-[0.25em] mx-[0em] overflow-hidden break-words text-xs font-semibold text-tundora"
                          style={{
                            display: '-webkit-box',
                            webkitBoxOrient: 'vertical',
                            webkitLineClamp: 2,
                          }}
                        >
                          Infaq Yatim: Kebahagiaan untuk 500 anak-anak Yatim
                        </span>
                        <div className="my-[0.25em] mx-[0em] flex w-full items-center align-middle text-xs text-[rgba(0,0,0,0.9)]">
                          <span className="overflow-hidden text-xs whitespace-nowrap">
                            Yuk Peduli
                          </span>
                          <img
                            className="ml-[0.25em] h-3"
                            src="https://assets.kitabisa.cc/images/icons/icon__verified-org.svg"
                            alt="icon__badge"
                            width="31"
                            height="12"
                            fetchpriority="low"
                            decoding="auto"
                          />
                        </div>
                        <div className="mx-[0em] my-[0.25em]">
                          <div
                            data-testid="progressBar"
                            className="style__Track-sc-__sc-15i3suc-0 clbckc"
                          >
                            <div
                              color="primary"
                              data-testid="progressBarFiller"
                              className="style__Filler-sc-__sc-15i3suc-1 bLoDes"
                            ></div>
                          </div>
                        </div>
                        <div className="my-[0.25em] mx-[0em] flex w-full justify-between">
                          <div className="flex flex-col">
                            <span className="text-[11px] text-gray-900">Terkumpul</span>
                            <span className="text-sm font-bold">Rp 1.068.856.879</span>
                          </div>
                          <div className="flex flex-col text-right">
                            <span className="text-xs font-normal text-gray-900">Sisa hari</span>
                            <span className="text-sm">
                              <strong> 1031 </strong>
                            </span>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="h-px bg-mercury"></div>
                  </a>
                  <a
                    data-testid="cardlink-pilih-kategori-favoritmu"
                    className="text-tundora no-underline"
                    href="/campaign/yukinfaqyatim"
                    id="347492-347492"
                  >
                    <div className="my-[1em] mx-[0em] flex items-center bg-white leading-[1.25em]">
                      <figure className="m-0 mr-5 flex aspect-[16/9] h-fit flex-1 items-center justify-center">
                        <img
                          alt="Infaq Yatim: Kebahagiaan untuk 500 anak-anak Yatim"
                          srcSet="https://thediplomat.com/wp-content/uploads/2015/11/sizes/td-story-s-2/thediplomat_2015-11-11_15-17-05.jpg"
                          src="https://thediplomat.com/wp-content/uploads/2015/11/sizes/td-story-s-2/thediplomat_2015-11-11_15-17-05.jpg"
                          width="256"
                          height="144"
                          decoding="async"
                          data-nimg="1"
                          className="h-full w-full rounded object-fill"
                          loading="lazy"
                          style={{ color: 'transparent' }}
                        />
                      </figure>
                      <div className="flex max-w-[45%] flex-1 flex-col justify-between">
                        <span
                          className="my-[0.25em] mx-[0em] overflow-hidden break-words text-xs font-semibold text-tundora"
                          style={{
                            display: '-webkit-box',
                            webkitBoxOrient: 'vertical',
                            webkitLineClamp: 2,
                          }}
                        >
                          Infaq Yatim: Kebahagiaan untuk 500 anak-anak Yatim
                        </span>
                        <div className="my-[0.25em] mx-[0em] flex w-full items-center align-middle text-xs text-[rgba(0,0,0,0.9)]">
                          <span className="overflow-hidden text-xs whitespace-nowrap">
                            Yuk Peduli
                          </span>
                          <img
                            className="ml-[0.25em] h-3"
                            src="https://assets.kitabisa.cc/images/icons/icon__verified-org.svg"
                            alt="icon__badge"
                            width="31"
                            height="12"
                            fetchpriority="low"
                            decoding="auto"
                          />
                        </div>
                        <div className="mx-[0em] my-[0.25em]">
                          <div
                            data-testid="progressBar"
                            className="style__Track-sc-__sc-15i3suc-0 clbckc"
                          >
                            <div
                              color="primary"
                              data-testid="progressBarFiller"
                              className="style__Filler-sc-__sc-15i3suc-1 bLoDes"
                            ></div>
                          </div>
                        </div>
                        <div className="my-[0.25em] mx-[0em] flex w-full justify-between">
                          <div className="flex flex-col">
                            <span className="text-[11px] text-gray-900">Terkumpul</span>
                            <span className="text-sm font-bold">Rp 1.068.856.879</span>
                          </div>
                          <div className="flex flex-col text-right">
                            <span className="text-xs font-normal text-gray-900">Sisa hari</span>
                            <span className="text-sm">
                              <strong> 1031 </strong>
                            </span>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="h-px bg-mercury"></div>
                  </a>
                  <a
                    data-testid="cardlink-pilih-kategori-favoritmu"
                    className="text-tundora no-underline"
                    href="/campaign/yukinfaqyatim"
                    id="347492-347492"
                  >
                    <div className="my-[1em] mx-[0em] flex items-center bg-white leading-[1.25em]">
                      <figure className="m-0 mr-5 flex aspect-[16/9] h-fit flex-1 items-center justify-center">
                        <img
                          alt="Infaq Yatim: Kebahagiaan untuk 500 anak-anak Yatim"
                          srcSet="https://thediplomat.com/wp-content/uploads/2015/11/sizes/td-story-s-2/thediplomat_2015-11-11_15-17-05.jpg"
                          src="https://thediplomat.com/wp-content/uploads/2015/11/sizes/td-story-s-2/thediplomat_2015-11-11_15-17-05.jpg"
                          width="256"
                          height="144"
                          decoding="async"
                          data-nimg="1"
                          className="h-full w-full rounded object-fill"
                          loading="lazy"
                          style={{ color: 'transparent' }}
                        />
                      </figure>
                      <div className="flex max-w-[45%] flex-1 flex-col justify-between">
                        <span
                          className="my-[0.25em] mx-[0em] overflow-hidden break-words text-xs font-semibold text-tundora"
                          style={{
                            display: '-webkit-box',
                            webkitBoxOrient: 'vertical',
                            webkitLineClamp: 2,
                          }}
                        >
                          Infaq Yatim: Kebahagiaan untuk 500 anak-anak Yatim
                        </span>
                        <div className="my-[0.25em] mx-[0em] flex w-full items-center align-middle text-xs text-[rgba(0,0,0,0.9)]">
                          <span className="overflow-hidden text-xs whitespace-nowrap">
                            Yuk Peduli
                          </span>
                          <img
                            className="ml-[0.25em] h-3"
                            src="https://assets.kitabisa.cc/images/icons/icon__verified-org.svg"
                            alt="icon__badge"
                            width="31"
                            height="12"
                            fetchpriority="low"
                            decoding="auto"
                          />
                        </div>
                        <div className="mx-[0em] my-[0.25em]">
                          <div
                            data-testid="progressBar"
                            className="style__Track-sc-__sc-15i3suc-0 clbckc"
                          >
                            <div
                              color="primary"
                              data-testid="progressBarFiller"
                              className="style__Filler-sc-__sc-15i3suc-1 bLoDes"
                            ></div>
                          </div>
                        </div>
                        <div className="my-[0.25em] mx-[0em] flex w-full justify-between">
                          <div className="flex flex-col">
                            <span className="text-[11px] text-gray-900">Terkumpul</span>
                            <span className="text-sm font-bold">Rp 1.068.856.879</span>
                          </div>
                          <div className="flex flex-col text-right">
                            <span className="text-xs font-normal text-gray-900">Sisa hari</span>
                            <span className="text-sm">
                              <strong> 1031 </strong>
                            </span>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="h-px bg-mercury"></div>
                  </a>
                </div>
                </div>
              </div>

              <div
                aria-hidden="true"
                data-testid="link-lihat-semua-pilih-kategori-favoritmu"
                className="relative my-[1em] mx-auto w-[160px]  cursor-pointer rounded-[15px] bg-[#e7f5ff] p-[5px] text-center text-[12px] text-[#10a8e5]"
              >
                Lihat Semua{' '}
                <span className="absolute top-[-10px] right-[15px] translate-y-2/4">
                  <svg
                    width="24px"
                    height="24px"
                    viewBox="0 0 24 24"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                    role="img"
                    className="w-3"
                  >
                    <path
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M6.389 2.389a1.327 1.327 0 0 1 1.876 0l8.673 8.673a1.326 1.326 0 0 1 0 1.876l-8.673 8.673a1.327 1.327 0 0 1-1.876-1.876L14.124 12 6.389 4.265a1.327 1.327 0 0 1 0-1.876Z"
                      fill="#10A8E5"
                    ></path>
                  </svg>
                </span>
              </div>

              {/*  */}
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  )
}
