import React, { useState, useRef } from "react";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import TweetEmbed from 'react-tweet-embed'
import styles from "../styles/Home.module.css";
import { Navigation, Pagination, Scrollbar, A11y } from "swiper";
import { Swiper, SwiperSlide } from "swiper/react";
import SwiperCore, { Autoplay } from "swiper";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Notice from "@/components/Notice";
import SubscribeForm from "@/components/SubscribeForm";
import QuoteLine from "@/components/QuoteLine";

import banner from "@/img/banner.jpg";
import kado from "@/img/kadountukasmat.jpg";
import kebaikan from "@/img/kebaikantanpaputus.jpg";
import amanah from "@/img/lazmizanamanah.jpg";
import arrowLeft from "@/img/icon_arrow-left.png";
import arrowRight from "@/img/icon_arrow-right.png";

import meme1 from "@/img/meme1.jpg";
import meme2 from "@/img/meme2.jpg";
import meme3 from "@/img/meme3.jpg";
import meme4 from "@/img/meme4.jpg";
import meme5 from "@/img/meme5.jpg";
import meme6 from "@/img/meme6.jpg";
import meme7 from "@/img/meme7.jpg";
import meme8 from "@/img/meme8.jpg";
import meme9 from "@/img/meme9.jpg";
import meme10 from "@/img/meme10.jpg";
import meme11 from "@/img/meme11.jpg";
import meme12 from "@/img/meme12.jpg";
import meme13 from "@/img/meme13.jpg";

import funny1 from "@/img/funny1.jpg";

export default function Home() {
  SwiperCore.use([Autoplay]);

  let scrl = useRef(null);
  const shiftN = 230;
  const [scrollX, setscrollX] = useState(0);
  const [scrolEnd, setscrolEnd] = useState(false);

  const slide = (shift) => {
    scrl.current.scrollLeft += shift;
    setscrollX(scrollX + shift);

    if (
      Math.floor(scrl.current.scrollWidth - scrl.current.scrollLeft) <=
      scrl.current.offsetWidth
    ) {
      setscrolEnd(true);
    } else {
      setscrolEnd(false);
    }
  };

  const scrollCheck = () => {
    setscrollX(scrl.current.scrollLeft);
    if (
      Math.floor(scrl.current.scrollWidth - scrl.current.scrollLeft) <=
      scrl.current.offsetWidth
    ) {
      setscrolEnd(true);
    } else {
      setscrolEnd(false);
    }
  };

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className="flex bg-white min-h-screen pt-[60px] md:pt-[100px]">
        <div className="flex flex-row w-full">
          <div className="flex flex-1 flex-col items-center justify-center relative">
            <div className="flex flex-1 flex-col pb-18 max-w-md md:max-w-2xl">
              <Notice />
              <div id="template_horizontal-image-slider">
                <div className="default-banner-slider relative pt-[16px] mb-[1em] h-full">
                  <Swiper
                    modules={[Pagination, A11y]}
                    slidesPerView={1}
                    loop={true}
                    autoplay={{
                      delay: 4000,
                    }}
                    pagination={{ clickable: true }}
                  >
                    <SwiperSlide>
                      <Image src={banner} />
                    </SwiperSlide>
                    <SwiperSlide>
                      <Image src={kado} />
                    </SwiperSlide>
                    <SwiperSlide>
                      <Image src={amanah} />
                    </SwiperSlide>
                    <SwiperSlide>
                      <Image src={kebaikan} />
                    </SwiperSlide>
                  </Swiper>
                </div>
              </div>

              {/* <div className="py-2 pb-5 overflow-auto overflow-y-auto custom-scrollbar">
                <div className="inline-flex space-x-4">
                  <Link href="#">
                    <div className="relative flex-col justify-center w-32 md:w-48 space-y-2 border p-2 shadow-lg rounded">
                      <div className="relative block overflow-hidden bg-white shadow flex rounded">
                        <Image
                          src={meme1}
                          alt=""
                          className="relative w-full"
                        />
                      </div>

                      <div className="flex text-center2 pt-1 md:pt-1 text-sm capitalize">
                        <span className="text-[12px] font-semibold text-gray-800">
                          600 Yatim Dhuafa Ingin Jadi Penghafal Al-Qur'an
                        </span>
                      </div>

                      <div className="flex flex-row justify-between text-center2 pt-1 md:pt-1 text-sm capitalize">
                        <span className="text-xs font-semibold">Pondok Al Ibadah</span>
                        <div className="">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            className="h-4 w-4 text-blue-500"
                            viewBox="0 0 20 20"
                            fill="currentColor"
                          >
                            <path
                              fillRule="evenodd"
                              d="M6.267 3.455a3.066 3.066 0 001.745-.723 3.066 3.066 0 013.976 0 3.066 3.066 0 001.745.723 3.066 3.066 0 012.812 2.812c.051.643.304 1.254.723 1.745a3.066 3.066 0 010 3.976 3.066 3.066 0 00-.723 1.745 3.066 3.066 0 01-2.812 2.812 3.066 3.066 0 00-1.745.723 3.066 3.066 0 01-3.976 0 3.066 3.066 0 00-1.745-.723 3.066 3.066 0 01-2.812-2.812 3.066 3.066 0 00-.723-1.745 3.066 3.066 0 010-3.976 3.066 3.066 0 00.723-1.745 3.066 3.066 0 012.812-2.812zm7.44 5.252a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                              clipRule="evenodd"
                            />
                          </svg>
                        </div>
                      </div>

                      <div className="overflow-hidden relative flex-1 rounded">
                        <div className="border-b-4 border-gray-300 rounded"></div>
                        <div className="absolute inset-x-0 top-0 -translate-x-4 border-b-4 border-blue-500 rounded transform hover:border-green-200"></div>
                      </div>

                      <div className="flex flex-col text-center2 pt-1 md:pt-1 text-sm capitalize">
                        <span className="text-[10px] font-semibold text-gray-600">Terkumpul</span>
                        <div>
                          <span className="text-sm pt-1 text-gray-900 font-bold">
                            Rp. 2.716.902.142
                          </span>
                        </div>
                      </div>
                    </div>
                  </Link>
                </div>
              </div> */}
              {/*  */}

              <div className="relative">
                <div className="my-4 mx-0 flex items-center justify-between">
                  <h1
                    data-testid="title-pilihan-kitabisa"
                    // className="m-0 text-lg text-gray-900 font-bold"
                    className="mt-0 text-md md:text-lg text-gray-900 font-semibold md:font-bold"
                  >
                    Riddles
                  </h1>
                  <a>
                    <span className="m-0 text-sm text-blue-400 cursor-pointer">
                      Lihat Lainnya
                    </span>
                  </a>
                </div>
                <div className="relative">
                  {scrollX !== 0 && (
                    <div className=" top-[40%] left-0 ">
                      <Image
                        className="none absolute top-[40%] left-0 z-10 cursor-pointer"
                        src={arrowLeft}
                        alt="arrow left"
                        decoding="auto"
                        fetchpriority="auto"
                        onClick={() => slide(-shiftN)}
                      />
                    </div>
                  )}
                  {!scrolEnd && (
                    <div className=" top-[40%] right-0">
                      <Image
                        data-testid="arrow-right-pilihan-kitabisa"
                        className="none absolute top-[40%] right-0 z-10 cursor-pointer"
                        alt="arrow right"
                        src={arrowRight}
                        decoding="auto"
                        fetchpriority="auto"
                        onClick={() => slide(+shiftN)}
                      />
                    </div>
                  )}

                  {/*  */}
                  <div
                    className="mb-[1em] flex flex-row overflow-x-auto scroll-smooth"
                    ref={scrl}
                    onScroll={scrollCheck}
                  >
                    <div className="text‑inherit mt-0 mr-[1em] mb-[1em] cursor-pointer no-underline">
                      <div className="w-[250px]">
                        <div
                          className="flex flex-col rounded-[4px]"
                          style={{
                            boxShadow:
                              "rgba(152, 152, 152, 0.2) 0px 2px 8px 1px",
                            border: "0.5px solid rgba(0, 0, 0, 0.1)",
                          }}
                        >
                          <figure className="relative m-0 flex flex-1 items-center justify-center">
                            <Image
                              alt=""
                              src={meme5}
                              width="100"
                              height="100"
                              className="h-full w-full rounded object-cover"
                              style={{ color: "transparent" }}
                            />
                          </figure>
                        </div>
                      </div>
                    </div>
                    {/*  */}
                    <div className="text‑inherit mt-0 mr-[1em] mb-[1em] cursor-pointer no-underline">
                      <div className="w-[250px]">
                        <div
                          className="flex flex-col rounded-[4px]"
                          style={{
                            boxShadow:
                              "rgba(152, 152, 152, 0.2) 0px 2px 8px 1px",
                            border: "0.5px solid rgba(0, 0, 0, 0.1)",
                          }}
                        >
                          <figure className="relative m-0 flex flex-1 items-center justify-center">
                            <Image
                              alt=""
                              src={meme6}
                              width="100"
                              height="100"
                              className="h-full w-full rounded object-cover"
                              style={{ color: "transparent" }}
                            />
                          </figure>
                        </div>
                      </div>
                    </div>
                    {/*  */}
                    <div className="text‑inherit mt-0 mr-[1em] mb-[1em] cursor-pointer no-underline">
                      <div className="w-[250px]">
                        <div
                          className="flex flex-col rounded-[4px]"
                          style={{
                            boxShadow:
                              "rgba(152, 152, 152, 0.2) 0px 2px 8px 1px",
                            border: "0.5px solid rgba(0, 0, 0, 0.1)",
                          }}
                        >
                          <figure className="relative m-0 flex flex-1 items-center justify-center">
                            <Image
                              alt=""
                              src={meme7}
                              width="100"
                              height="100"
                              className="h-full w-full rounded object-cover"
                              style={{ color: "transparent" }}
                            />
                          </figure>
                        </div>
                      </div>
                    </div>
                    {/*  */}
                    <div className="text‑inherit mt-0 mr-[1em] mb-[1em] cursor-pointer no-underline">
                      <div className="w-[250px]">
                        <div
                          className="flex flex-col rounded-[4px]"
                          style={{
                            boxShadow:
                              "rgba(152, 152, 152, 0.2) 0px 2px 8px 1px",
                            border: "0.5px solid rgba(0, 0, 0, 0.1)",
                          }}
                        >
                          <figure className="relative m-0 flex flex-1 items-center justify-center">
                            <Image
                              alt=""
                              src={meme5}
                              width="100"
                              height="100"
                              className="h-full w-full rounded object-cover"
                              style={{ color: "transparent" }}
                            />
                          </figure>
                        </div>
                      </div>
                    </div>
                    {/*  */}
                    <div className="text‑inherit mt-0 mr-[1em] mb-[1em] cursor-pointer no-underline">
                      <div className="w-[250px]">
                        <div
                          className="flex flex-col rounded-[4px]"
                          style={{
                            boxShadow:
                              "rgba(152, 152, 152, 0.2) 0px 2px 8px 1px",
                            border: "0.5px solid rgba(0, 0, 0, 0.1)",
                          }}
                        >
                          <figure className="relative m-0 flex z-0 flex-1 items-center justify-center">
                            <Image
                              alt=""
                              src={meme8}
                              width="100"
                              height="100"
                              className="h-full z-0 w-full rounded object-cover"
                              style={{ color: "transparent" }}
                            />
                          </figure>
                        </div>
                      </div>
                    </div>
                    {/*  */}
                    <div
                      data-testid="link-lihat-semua-pilihan-kitabisa"
                      className="text‑inherit mt-0 mr-2 mb-4 cursor-pointer no-underline"
                    >
                      <div className="flex h-full w-[150px] flex-col justify-center text-center text-[#00aeef]">
                        <div className="text-base">
                          <svg
                            width="32px"
                            height="32px"
                            viewBox="0 0 24 24"
                            fill="none"
                            xmlns="http://www.w3.org/2000/svg"
                            role="img"
                            className="inline"
                          >
                            <path
                              fillRule="evenodd"
                              clipRule="evenodd"
                              d="M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18ZM1 12C1 5.925 5.925 1 12 1s11 4.925 11 11-4.925 11-11 11S1 18.075 1 12Z"
                              fill="#10A8E5"
                            ></path>
                            <path
                              d="M12.204 8.352c-.4-.443-.378-1.139.049-1.554a1.03 1.03 0 0 1 1.495.05l3.966 4.4a1.132 1.132 0 0 1 0 1.504l-3.966 4.4a1.03 1.03 0 0 1-1.495.05 1.131 1.131 0 0 1-.049-1.554l2.297-2.548H7.1a1.1 1.1 0 0 1 0-2.2h7.4l-2.296-2.548Z"
                              fill="#10A8E5"
                            ></path>
                          </svg>
                        </div>
                        <span className="m-0 text-base font-bold">
                          Lihat Semua
                        </span>
                      </div>
                    </div>
                    {/*  */}
                  </div>
                </div>
              </div>

              <div>
                <h1
                  data-testid="title-pilih-kategori-favoritmu"
                  // className="mx-0 my-[1em] text-[16px] font-semibold leading-6 text-[#4a4a4a]"
                  className="mt-5 text-md md:text-lg text-gray-900 font-semibold md:font-bold"
                >
                  Blog
                </h1>
                <div className="flex w-full space-x-4">
                  <div>
                    <a
                      data-testid="cardlink-pilih-kategori-favoritmu"
                      className="text-tundora no-underline"
                      href="/campaign/yukinfaqyatim"
                      id="347492-347492"
                    >
                      <div className="my-[1em] mx-[0em] flex items-center w-full bg-white leading-[1.25em]">
                        <figure className="m-0 mr-5 flex aspect-[16/9] h-fit flex-1 items-center justify-center">
                          <Image
                            alt="Infaq Yatim: Kebahagiaan untuk 500 anak-anak Yatim"
                            src={meme13}
                            width="256"
                            height="144"
                            className="h-full w-full rounded object-fill"
                            style={{ color: "transparent" }}
                          />
                        </figure>
                        <div className="flex w-2/3 max-w-[45%] flex-1 flex-col space-x-y-1 md:space-y-2">
                          <span
                            className="my-[0.25em] mx-[0em] overflow-hidden break-words text-sm md:text-lg leading-tight md:leading-tight font-semibold text-tundora"
                            style={{
                              display: "-webkit-box",
                            }}
                          >
                            80 Funny Work Memes to Keep You Laughing Through the
                            Week
                          </span>
                          <span className="text-xs md:text-lg leading-tight md:leading-tight break-words text-justify">
                            Whether you're waiting for the weekend or
                            commiserating about your job, these funny work memes
                            will help you cope
                          </span>
                        </div>
                      </div>
                      <div className="h-px bg-mercury"></div>
                    </a>
                    <a
                      data-testid="cardlink-pilih-kategori-favoritmu"
                      className="text-tundora no-underline"
                      href="/campaign/yukinfaqyatim"
                      id="347492-347492"
                    >
                      <div className="my-[1em] mx-[0em] flex items-center w-full bg-white leading-[1.25em]">
                        <figure className="m-0 mr-5 flex aspect-[16/9] h-fit flex-1 items-center justify-center">
                          <Image
                            alt="Infaq Yatim: Kebahagiaan untuk 500 anak-anak Yatim"
                            src={meme11}
                            width="100%"
                            height="100%"
                            className="h-full w-full rounded object-fill"
                            style={{ color: "transparent" }}
                          />
                        </figure>
                        <div className="flex w-2/3 max-w-[45%] flex-1 flex-col space-x-y-1 md:space-y-2">
                          <span
                            className="my-[0.25em] mx-[0em] overflow-hidden break-words text-sm md:text-lg leading-tight md:leading-tight font-semibold text-tundora"
                            style={{
                              display: "-webkit-box",
                            }}
                          >
                            80 Funny Work Memes to Keep You Laughing Through the
                            Week
                          </span>
                          <span className="text-xs md:text-lg leading-tight md:leading-tight break-words text-justify">
                            Whether you're waiting for the weekend or
                            commiserating about your job, these funny work memes
                            will help you cope
                          </span>
                        </div>
                      </div>
                      <div className="h-px bg-mercury"></div>
                    </a>
                    {/*  */}
                    <div className="flex min-w-0 flex-1 flex-col">
                      <div className="flex flex-row text-gray-33 dark:text-gray-cc md:justify-start">
                        <div className="flex flex-row flex-wrap items-center font-polysans text-11 uppercase leading-130 tracking-15 text-gray-33 dark:text-gray-cc">
                          <a
                            className="relative z-10 mr-8 font-bold hover:shadow-underline-inherit"
                            href="/authors/sean-hollister"
                          >
                            Sean Hollister
                          </a>
                          <a
                            className="relative z-10 mr-8 font-bold hover:shadow-underline-inherit"
                            href="/2023/6/14/23761257/the-first-sneak-peek-at-the-babylon-5-animated-movie"
                          >
                            <time
                              className="flex items-center font-normal"
                              dateTime="2023-06-14T19:33:31.303Z"
                            >
                              2:33 AM GMT+7
                            </time>
                          </a>
                        </div>
                        <div className="relative z-10 flex flex-row items-center md:flex-row">
                          <button aria-label="Copy link">
                            <svg
                              className="fill-gray-63 transition hover:fill-black dark:hover:fill-white"
                              width="20"
                              height="20"
                              fill="none"
                              viewBox="0 0 40 40"
                              xmlns="http://www.w3.org/2000/svg"
                            >
                              <title>Link</title>
                              <path d="M16.9691 32.9499C14.2358 35.6832 9.78321 35.6832 7.04996 32.9499C4.31671 30.2166 4.31665 25.764 7.04996 23.0307L12.5606 17.52C15.294 14.7867 19.7465 14.7867 22.4798 17.52C22.704 17.7383 22.8315 18.037 22.8337 18.3499C22.8359 18.6628 22.7125 18.9634 22.4912 19.1846C22.2702 19.4059 21.9693 19.5293 21.6568 19.5271C21.3439 19.5249 21.0449 19.3975 20.8266 19.1732C18.9805 17.3271 16.0599 17.3271 14.2137 19.1732L8.70306 24.6839C6.85694 26.53 6.85694 29.4507 8.70306 31.2968C10.5492 33.1429 13.4698 33.1426 15.3159 31.2968L20.551 26.0614V26.0617C20.7693 25.8375 21.0683 25.71 21.3811 25.7078C21.694 25.7056 21.9946 25.829 22.2159 26.0503C22.4368 26.2716 22.5602 26.5722 22.5581 26.885C22.5559 27.1979 22.4284 27.4966 22.2042 27.7149L16.9691 32.9499ZM27.4394 22.4796C24.706 25.2129 20.2535 25.2129 17.5202 22.4796V22.4799C17.296 22.2616 17.1685 21.9629 17.1663 21.65C17.1644 21.3372 17.2875 21.0366 17.5088 20.8153C17.7301 20.5941 18.0307 20.4707 18.3435 20.4728C18.6564 20.475 18.9551 20.6025 19.1734 20.8267C21.0195 22.6728 23.9401 22.6728 25.7863 20.8267L31.2969 15.316C33.1431 13.4699 33.1431 10.5493 31.2969 8.70316C29.4508 6.85704 26.5302 6.85704 24.6841 8.70316L19.449 13.9382C19.2307 14.1625 18.9317 14.2902 18.6189 14.2924C18.306 14.2946 18.0054 14.1712 17.7841 13.9499C17.5629 13.7286 17.4395 13.428 17.4417 13.1149C17.4438 12.802 17.5713 12.503 17.7958 12.285L23.0309 7.04999C25.7642 4.31667 30.2168 4.31667 32.95 7.04999C35.6833 9.7833 35.6834 14.2359 32.95 16.9691L27.4394 22.4798L27.4394 22.4796Z"></path>
                            </svg>
                          </button>
                        </div>
                      </div>
                      <div className="flex flex-col space-y-2 font-polysans text-black dark:text-gray-ef leading-tight bg-pink-200">
                        <div className="inline pr-4 text-[17px] font-bold md:text-[17px]">
                          The first sneak peek at the Babylon 5 animated movie.
                        </div>
                        <p className="duet--article--dangerously-set-cms-markup inline font-fkroman text-gray-33 dark:text-gray-ef [&amp;_a]:relative [&amp;_a]:z-10  [&amp;_a:hover]:text-blurple [&amp;_a:hover]:shadow-underline-blurple dark:[&amp;_a:hover]:text-franklin dark:[&amp;_a:hover]:shadow-underline-franklin [&amp;_a]:shadow-underline-blurple dark:[&amp;_a]:shadow-underline-franklin">
                          A full trailer, release date, and what sounds like
                          preorders are coming tomorrow,{" "}
                          <a href="https://twitter.com/straczynski/status/1669011815446249475?s=46&amp;t=g01btXivdkkmtc6rgtfM-w">
                            tweets series creator J. Michael Straczynski
                          </a>
                          . Here’s{" "}
                          <a href="/2023/5/10/23718851/babylon-5-the-road-home-animated-movie-synopsis-cast">
                            everything else
                          </a>{" "}
                          <a href="/2023/5/3/23708919/babylon-5-secret-project-jms-straczynski">
                            we know
                          </a>{" "}
                          about<strong> </strong>
                          <em>Babylon 5: The Road Home.</em>
                        </p>
                        <br />
                      </div>
                      <div className="pt-0 flex w-full mx-auto justify-center items-center bg-orange-200">
                        <div className="min-h-[270px] quickpost mb-0 w-full md:max-w-[460px] relative z-10 overflow-x-hidden md:max-w-full">
                          <div>
                            <div
                              className="aspect-w-16 aspect-h-9 flex w-[550px] my-[10px] overflow-y-hidden"
                            >
                              <iframe
                                id="twitter-widget-0"
                                frameBorder="0"
                                allowtransparency="true"
                                allowFullScreen="true"
                                className="static overflow-y-hidden w-[445px] h-[638px] flex-1"
                                // style={{ position: 'static', visibility: 'visible', width: '445px', height: '638px', display: 'block', flexGrow: 1 }}
                                title="Twitter Tweet"
                                src="https://platform.twitter.com/embed/Tweet.html?dnt=false&amp;embedId=twitter-widget-0&amp;features=eyJ0ZndfdGltZWxpbmVfbGlzdCI6eyJidWNrZXQiOltdLCJ2ZXJzaW9uIjpudWxsfSwidGZ3X2ZvbGxvd2VyX2NvdW50X3N1bnNldCI6eyJidWNrZXQiOnRydWUsInZlcnNpb24iOm51bGx9LCJ0ZndfdHdlZXRfZWRpdF9iYWNrZW5kIjp7ImJ1Y2tldCI6Im9uIiwidmVyc2lvbiI6bnVsbH0sInRmd19yZWZzcmNfc2Vzc2lvbiI6eyJidWNrZXQiOiJvbiIsInZlcnNpb24iOm51bGx9LCJ0ZndfZm9zbnJfc29mdF9pbnRlcnZlbnRpb25zX2VuYWJsZWQiOnsiYnVja2V0Ijoib24iLCJ2ZXJzaW9uIjpudWxsfSwidGZ3X21peGVkX21lZGlhXzE1ODk3Ijp7ImJ1Y2tldCI6InRyZWF0bWVudCIsInZlcnNpb24iOm51bGx9LCJ0ZndfZXhwZXJpbWVudHNfY29va2llX2V4cGlyYXRpb24iOnsiYnVja2V0IjoxMjA5NjAwLCJ2ZXJzaW9uIjpudWxsfSwidGZ3X3Nob3dfYmlyZHdhdGNoX3Bpdm90c19lbmFibGVkIjp7ImJ1Y2tldCI6Im9uIiwidmVyc2lvbiI6bnVsbH0sInRmd19kdXBsaWNhdGVfc2NyaWJlc190b19zZXR0aW5ncyI6eyJidWNrZXQiOiJvbiIsInZlcnNpb24iOm51bGx9LCJ0ZndfdXNlX3Byb2ZpbGVfaW1hZ2Vfc2hhcGVfZW5hYmxlZCI6eyJidWNrZXQiOiJvbiIsInZlcnNpb24iOm51bGx9LCJ0ZndfdmlkZW9faGxzX2R5bmFtaWNfbWFuaWZlc3RzXzE1MDgyIjp7ImJ1Y2tldCI6InRydWVfYml0cmF0ZSIsInZlcnNpb24iOm51bGx9LCJ0ZndfbGVnYWN5X3RpbWVsaW5lX3N1bnNldCI6eyJidWNrZXQiOnRydWUsInZlcnNpb24iOm51bGx9LCJ0ZndfdHdlZXRfZWRpdF9mcm9udGVuZCI6eyJidWNrZXQiOiJvbiIsInZlcnNpb24iOm51bGx9fQ%3D%3D&amp;frame=false&amp;hideCard=false&amp;hideThread=false&amp;id=1669011815446249475&amp;lang=en&amp;origin=https%3A%2F%2Fwww.theverge.com%2F&amp;sessionId=ab51efdc2d73433f8566ff9c73cb337ea43e15f3&amp;siteScreenName=verge&amp;theme=dark&amp;widgetsVersion=aaf4084522e3a%3A1674595607486&amp;width=550px"
                                data-tweet-id="1669011815446249475"
                              ></iframe>
                            </div>
                            <script
                              async=""
                              src="https://platform.twitter.com/widgets.js"
                              charSet="utf-8"
                            ></script>
                            
                          </div>
                        </div>
                      </div>
                    </div>
                    {/*  */}
                    <a
                      data-testid="cardlink-pilih-kategori-favoritmu"
                      className="text-tundora no-underline"
                      href="/campaign/yukinfaqyatim"
                      id="347492-347492"
                    >
                      <div className="my-[1em] mx-[0em] flex items-center w-full bg-white leading-[1.25em]">
                        <figure className="m-0 mr-5 flex aspect-[16/9] h-fit flex-1 items-center justify-center">
                          <Image
                            alt="Infaq Yatim: Kebahagiaan untuk 500 anak-anak Yatim"
                            src={meme12}
                            width="256"
                            height="144"
                            className="h-full w-full rounded object-fill"
                            style={{ color: "transparent" }}
                          />
                        </figure>
                        <div className="flex w-2/3 max-w-[45%] flex-1 flex-col space-x-y-1 md:space-y-2">
                          <span
                            className="my-[0.25em] mx-[0em] overflow-hidden break-words text-sm md:text-lg leading-tight md:leading-tight font-semibold text-tundora"
                            style={{
                              display: "-webkit-box",
                            }}
                          >
                            80 Funny Work Memes to Keep You Laughing Through the
                            Week
                          </span>
                          <span className="text-xs md:text-lg leading-tight md:leading-tight break-words text-justify">
                            Whether you're waiting for the weekend or
                            commiserating about your job, these funny work memes
                            will help you cope
                          </span>
                        </div>
                      </div>
                      <div className="h-px bg-mercury"></div>
                    </a>
                  </div>
                </div>
              </div>

              <div className="flex items-center justify-center px-3 py-2 space-x-1 md:space-x-3 my-[1em] mx-auto w-[160px] md:w-[190px] cursor-pointer rounded-full bg-[#e7f5ff]  text-center text-sm md:text-lg text-[#10a8e5]">
                <span>Lihat Semua</span>
                <span className="">
                  <svg
                    viewBox="0 0 24 24"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                    role="img"
                    className="w-3"
                  >
                    <path
                      fillRule="evenodd"
                      clipRule="evenodd"
                      d="M6.389 2.389a1.327 1.327 0 0 1 1.876 0l8.673 8.673a1.326 1.326 0 0 1 0 1.876l-8.673 8.673a1.327 1.327 0 0 1-1.876-1.876L14.124 12 6.389 4.265a1.327 1.327 0 0 1 0-1.876Z"
                      fill="#10A8E5"
                    ></path>
                  </svg>
                </span>
              </div>

              {/*  */}
              <QuoteLine />
            </div>
            <SubscribeForm />
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}
