import React from 'react'
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Notice from "@/components/Notice";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SubscribeForm from "@/components/SubscribeForm";
import QuoteRandom from "@/components/QuoteRandom";
import Pagination from "@/components/Pagination";
import Ava from '@/components/Ava';

import meme11 from "@/img/meme11.jpg";
import meme12 from "@/img/meme12.jpg";
import meme13 from "@/img/meme13.jpg";

import funny1 from "@/img/funny1.jpg";

const Funny = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className="flex bg-white min-h-screen pt-14 md:pt-[100px]">
        <div className="flex flex-row w-full">
          <div className="flex flex-1 flex-col items-center justify-center relative">
            <div className="flex flex-1 flex-col pb-18 max-w-md md:max-w-2xl ">
              <section className="w-full mx-auto  mt-10 md:mt-10 px-5 ">
                <h1 className="text-3xl font-bold tracking-tighter md:text-5xl lg:text-7xl">
                  1,000<span className="text-xl">s</span> more clicks <br />{" "}
                  with Automated Link Previews!
                </h1>
                <p className="max-w-3xl mt-6 text-lg font-medium md:text-xl lg:text-2xl">
                  Say goodbye to Canva! Create a template, integrate it into
                  your site once, and focus on creating great content.
                </p>

                <div>
                  <div className="pt-6">
                    <Image src={funny1} alt="" />
                  </div>
                  <div className="flex w-full space-x-4">
                    <div className="mt-8 grid grid-cols-1 md:grid-cols-2 gap-y-[32px] sm:gap-x-[32px]">
                      <Link href="/guides/dota-2/2023-dpc-ranking-who-is-going-to-ti12/">
                        <section class=" shadow hover:shadow-lg bg-white dark:bg-dark-neutral-50 dark:hover:bg-dark-neutral-300 text-neutral-900 dark:text-neutral-100 hover:cursor-pointer h-full group rounded-xl overflow-hidden">
                          <Image src={meme12} alt='' className='w-full h-48 object-cover' />
                          
                          <div class="px-4 py-4">
                            <div>
                              <div class="text-md leading-tight mb-4 text-neutral-600 dark:text-neutral-300 line-clamp-3">
                                <p>
                                  Find out which teams are ahead in the race to
                                  The International 12.
                                </p>
                              </div>
                              <div class="flex justify-between items-center">
                                <div class="flex items-center space-x-2">
                                  {/* <Image
                                    alt='Sarah "KZ" Zulkiflee'
                                    srcset="/_next/image/?url=https%3A%2F%2Fsecure.gravatar.com%2Favatar%2Fa6148229eade52f8c4ca557fc6f5d1db%3Fs%3D400%26d%3Dmm%26r%3Dg&amp;w=48&amp;q=75 1x, /_next/image/?url=https%3A%2F%2Fsecure.gravatar.com%2Favatar%2Fa6148229eade52f8c4ca557fc6f5d1db%3Fs%3D400%26d%3Dmm%26r%3Dg&amp;w=96&amp;q=75 2x"
                                    src={meme11}
                                    width="35"
                                    height="35"
                                    decoding="async"
                                    data-nimg="1"
                                    class="rounded-full mr-4"
                                    loading="lazy"
                                  /> */}
                                  <Ava username={'Sarah Zulkiflee'} size={35} />
                                  <div class="text-xs">
                                    <p class="text-sm font-semibold">
                                      Sarah &quot;KZ&quot; Zulkiflee
                                    </p>
                                  </div>
                                </div>
                                <div class="text-xs">
                                  <time datetime="2023-06-23T00:30:27">
                                    June 23, 2023
                                  </time>
                                </div>
                              </div>
                            </div>
                          </div>
                        </section>
                      </Link>
                      <Link href="/guides/dota-2/2023-dpc-ranking-who-is-going-to-ti12/">
                        <section class=" shadow hover:shadow-lg bg-white dark:bg-dark-neutral-50 dark:hover:bg-dark-neutral-300 text-neutral-900 dark:text-neutral-100 hover:cursor-pointer h-full group rounded-xl overflow-hidden">
                          <Image src={meme13} alt='' className='w-full h-48 object-cover' />
                          
                          <div class="px-4 py-4">
                            <div>
                              <div class="text-md leading-tight mb-4 text-neutral-600 dark:text-neutral-300 line-clamp-3">
                                <p>
                                  Find out which teams are ahead in the race to
                                  The International 12.
                                </p>
                              </div>
                              <div class="flex justify-between items-center">
                                <div class="flex items-center space-x-2">
                                <Ava username={'Sarah Zulkiflee'} size={35} />
                                  <div class="text-xs">
                                    <p class="text-sm font-semibold">
                                      Sarah &quot;KZ&quot; Zulkiflee
                                    </p>
                                  </div>
                                </div>
                                <div class="text-xs">
                                  <time datetime="2023-06-23T00:30:27">
                                    June 23, 2023
                                  </time>
                                </div>
                              </div>
                            </div>
                          </div>
                        </section>
                      </Link>
                      <Link href="/guides/dota-2/2023-dpc-ranking-who-is-going-to-ti12/">
                        <section class=" shadow hover:shadow-lg bg-white dark:bg-dark-neutral-50 dark:hover:bg-dark-neutral-300 text-neutral-900 dark:text-neutral-100 hover:cursor-pointer h-full group rounded-xl overflow-hidden">
                          <Image src={meme11} alt='' className='w-full h-48 object-cover' />
                          
                          <div class="px-4 py-4">
                            <div>
                              <div class="text-md leading-tight mb-4 text-neutral-600 dark:text-neutral-300 line-clamp-3">
                                <p>
                                  Find out which teams are ahead in the race to
                                  The International 12.
                                </p>
                              </div>
                              <div class="flex justify-between items-center">
                                <div class="flex items-center space-x-2">
                                <Ava username={'Sarah Zulkiflee'} size={35} />
                                  <div class="text-xs">
                                    <p class="text-sm font-semibold">
                                      Sarah &quot;KZ&quot; Zulkiflee
                                    </p>
                                  </div>
                                </div>
                                <div class="text-xs">
                                  <time datetime="2023-06-23T00:30:27">
                                    June 23, 2023
                                  </time>
                                </div>
                              </div>
                            </div>
                          </div>
                        </section>
                      </Link>
                      <Link href="/guides/dota-2/2023-dpc-ranking-who-is-going-to-ti12/">
                        <section class=" shadow hover:shadow-lg bg-white dark:bg-dark-neutral-50 dark:hover:bg-dark-neutral-300 text-neutral-900 dark:text-neutral-100 hover:cursor-pointer h-full group rounded-xl overflow-hidden">
                          <Image src={meme12} alt='' className='w-full h-48 object-cover' />
                          
                          <div class="px-4 py-4">
                            <div>
                              <div class="text-md leading-tight mb-4 text-neutral-600 dark:text-neutral-300 line-clamp-3">
                                <p>
                                  Find out which teams are ahead in the race to
                                  The International 12.
                                </p>
                              </div>
                              <div class="flex justify-between items-center">
                                <div class="flex items-center space-x-2">
                                  <Ava username={'Sarah Zulkiflee'} size={35} />
                                  <div class="text-xs">
                                    <p class="text-sm font-semibold">
                                      Sarah &quot;KZ&quot; Zulkiflee
                                    </p>
                                  </div>
                                </div>
                                <div class="flex justify-end text-xs">
                                  <time datetime="2023-06-23T00:30:27">
                                    June 23, 2023
                                  </time>
                                </div>
                              </div>
                            </div>
                          </div>
                        </section>
                      </Link>
                    </div>
                  </div>
                </div>
                <Pagination />
              </section>

              <QuoteRandom />
            </div>
            <SubscribeForm />
          </div>
        </div>
      </div>

      <Footer />
    </div>
  );
}

export default Funny;
